const state={spots:[],species:[],documents:[],sources:[],selectedSpot:null,selectedSpecies:null,conditionEngine:null};
const $=(q)=>document.querySelector(q);
const escapeHtml=(value)=>String(value??'').replace(/[&<>'"]/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const DATA_ROOT='data';

async function getJson(file){const response=await fetch(`${DATA_ROOT}/${file}`);if(!response.ok)throw new Error(`${file}: ${response.status}`);return response.json();}
async function getJsonOptional(file){try{return await getJson(file);}catch(error){console.warn(`Optional RICHFISH feed unavailable: ${file}`,error.message);return null;}}
function metric(label,value,note=''){return `<div class="metric"><small>${escapeHtml(label)}</small><strong>${escapeHtml(value)}</strong><span>${escapeHtml(note)}</span></div>`;}
function dataCard(label,value,note=''){return `<div class="data-card"><small>${escapeHtml(label)}</small><strong>${escapeHtml(value)}</strong><span>${escapeHtml(note)}</span></div>`;}
function scoreSpot(spot,speciesId){const live=state.conditionEngine?.spots?.[spot.id]?.species?.[speciesId];if(live)return live.recommendationScore;const match=spot.species.find(item=>item.id===speciesId);if(!match)return null;return match.baseScore;}
function recommendations(speciesId){const species=state.species.find(item=>item.id===speciesId);const liveRows=state.conditionEngine?.rankings?.[speciesId];if(Array.isArray(liveRows)&&liveRows.length){const spots=liveRows.map(row=>{const spot=state.spots.find(s=>s.id===row.spotId);return spot?{...spot,confidence:row.recommendationScore,conditionFit:row.conditionFit,dataConfidence:row.dataConfidence,siteFit:row.siteFit,factors:row.factors,activeCaveats:row.activeCaveats,legalGate:row.legalGate,modelSource:'Condition Engine v0.2'}:null;}).filter(Boolean);return {species,generatedAt:state.conditionEngine.generatedAt,methodology:'RICHFISH Condition Engine v0.2: site fit + live environmental condition fit, explicitly adjusted by authoritative-data coverage and freshness. Condition Fit is not catch probability.',spots};}const spots=state.spots.map(spot=>({...spot,confidence:scoreSpot(spot,speciesId),conditionFit:null,dataConfidence:0,modelSource:'Static fallback'})).filter(s=>s.confidence!==null).sort((a,b)=>b.confidence-a.confidence);return {species,generatedAt:new Date().toISOString(),methodology:'Static site-fit fallback because the live Condition Engine snapshot is unavailable.',spots};}

function cleanNumber(value,digits=1){const n=Number(value);return Number.isFinite(n)?n.toFixed(digits):null;}
function renderConditionStrip(){const s=state.spots[0];if(!s)return;const o=state.conditionEngine?.spots?.['point-pinole']?.observations||{};const cards=[];const currentText=o.current?.speedKnots!=null?cleanNumber(o.current.speedKnots,2)+' kt'+(o.current.towardCardinal?' toward '+o.current.towardCardinal:''):null;
if(o.waterLevelFt!=null)cards.push(metric('Richmond water level',cleanNumber(o.waterLevelFt,2)+' ft','NOAA CO-OPS · observed'));else cards.push(metric('Tide',s.conditions.tideTrend,'Prototype fallback'));
if(o.waterTemperatureF!=null)cards.push(metric('Water temp',cleanNumber(o.waterTemperatureF,1)+'°F','NOAA Richmond · observed'));else cards.push(metric('Water temp',s.conditions.waterTempF+'°F','Prototype fallback'));
if(currentText)cards.push(metric('Current',currentText,'NOAA SFBOFS · modeled'));else if(o.windMph!=null)cards.push(metric('Wind',cleanNumber(o.windMph,1)+' mph '+(o.windDirection||''),'NOAA Richmond · observed'));else cards.push(metric('Wind',s.conditions.windMph+' mph','Prototype fallback'));
if(o.salinityPsu!=null)cards.push(metric('Salinity',cleanNumber(o.salinityPsu,1)+' PSU','NOAA Richmond · observed'));else cards.push(metric('Salinity',s.conditions.salinityPsu+' PSU','Prototype fallback'));
if(o.freshwater?.value!=null)cards.push(metric('Sacramento inflow',Math.round(o.freshwater.value).toLocaleString()+' '+(o.freshwater.unit||''),'USGS · observed IV'));else cards.push(metric('Depth',s.conditions.depthFt,'Prototype fishing range'));
$('#condition-strip').innerHTML=cards.join('');}
function renderSpotList(filter=''){const list=state.spots.filter(s=>`${s.name} ${s.region}`.toLowerCase().includes(filter.toLowerCase()));$('#spot-list').innerHTML=list.map(s=>`<button class="select-item ${state.selectedSpot?.id===s.id?'active':''}" data-spot="${s.id}"><strong>${escapeHtml(s.name)}</strong><small>${escapeHtml(s.region)}</small></button>`).join('');document.querySelectorAll('[data-spot]').forEach(b=>b.onclick=()=>selectSpot(b.dataset.spot));}
function selectSpot(id){state.selectedSpot=state.spots.find(s=>s.id===id);renderSpotList($('#spot-search').value);renderSpotDetail();}
function renderSpotDetail(){const s=state.selectedSpot;if(!s)return;const live=state.conditionEngine?.spots?.[s.id];const o=live?.observations||{};const updated=state.conditionEngine?.generatedAt||s.updatedAt;const tide=o.tide?.trend?o.tide.trend.replace(/^./,x=>x.toUpperCase()):s.conditions.tideTrend;const current=o.current?.speedKnots!=null?`${cleanNumber(o.current.speedKnots,2)} kt toward ${o.current.towardCardinal||o.current.towardDegreesTrue||'grid'}`:'Unavailable';const currentNote=o.current?.trend?.direction?`SFBOFS · ${o.current.trend.direction}`:o.current?.validTime?`SFBOFS · valid ${new Date(o.current.validTime).toLocaleTimeString()}`:'SFBOFS unavailable';const temp=o.waterTemperatureF!=null?`${cleanNumber(o.waterTemperatureF,1)}°F`:`${s.conditions.waterTempF}°F (fallback)`;const sal=o.salinityPsu!=null?`${cleanNumber(o.salinityPsu,1)} PSU`:`${s.conditions.salinityPsu} PSU (fallback)`;const wind=o.windMph!=null?`${cleanNumber(o.windMph,1)} mph ${o.windDirection||''}`.trim():`${s.conditions.windMph} mph (fallback)`;const flow=o.freshwater?.value!=null?`${Math.round(o.freshwater.value).toLocaleString()} ${o.freshwater.unit||''}`.trim():'Unavailable';$('#spot-detail').classList.remove('loading');$('#spot-detail').innerHTML=`<div class="detail-top"><div><span class="badge">● Conditions ${new Date(updated).toLocaleString()}</span><h3>${escapeHtml(s.name)}</h3><p>${escapeHtml(s.region)} · ${escapeHtml(s.city)}</p></div><div><span class="eyebrow">ACCESS</span><p>${escapeHtml(s.access)}</p></div></div><div class="detail-grid">${dataCard('Tide',tide,live?'NOAA-derived':'Prototype fallback')}${dataCard('Current',current,currentNote)}${dataCard('Water',temp)}${dataCard('Salinity',sal)}${dataCard('Wind',wind)}${dataCard('Freshwater flow',flow,o.freshwater?.stationId||'USGS unavailable')}${dataCard('Depth',s.conditions.depthFt,'Static site profile')}${dataCard('Latitude',s.coordinates.lat)}${dataCard('Longitude',s.coordinates.lng)}</div><div class="info-layout"><div class="info-card"><small>Target fish</small><ul>${s.species.map(x=>`<li>${escapeHtml(state.species.find(sp=>sp.id===x.id)?.name||x.id)} — ${escapeHtml(x.activity)}</li>`).join('')}</ul></div><div class="info-card"><small>Recommended baits</small><ul>${s.recommendedBaits.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div><div class="info-card"><small>Recommended rigs</small><ul>${s.recommendedRigs.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div><div class="info-card"><small>Best windows</small><ul>${s.bestWindows.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div><div class="info-card"><small>Rumor report</small><ul>${s.reports.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div><div class="info-card"><small>Warnings / cautions</small><ul>${s.cautions.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div></div><div class="ray-note"><b>RAY'S CALL</b><br>“${escapeHtml(s.richmondRayNote)}”</div>`;}
function currentFactorLine(row){const f=row?.factors?.find(x=>x.id==='current');if(!f||f.value==null)return '';const d=f.details||{};const dir=d.towardCardinal||d.towardDegreesTrue||'grid';return `Current: ${cleanNumber(f.value,2)} kt toward ${dir} · current-fit ${f.score}%`;}
function renderSpeciesList(){$('#species-list').innerHTML=state.species.map(s=>`<button class="select-item ${state.selectedSpecies?.id===s.id?'active':''}" data-species="${s.id}"><strong>${s.icon} ${escapeHtml(s.name)}</strong><small>${escapeHtml(s.scientificName)}</small></button>`).join('');document.querySelectorAll('[data-species]').forEach(b=>b.onclick=()=>selectSpecies(b.dataset.species));}
function selectSpecies(id){state.selectedSpecies=state.species.find(s=>s.id===id);renderSpeciesList();renderFinder(recommendations(id));}
function renderFinder(result){const d=$('#finder-detail');d.classList.remove('loading');d.innerHTML=`<div class="detail-top"><div><span class="badge">● Generated ${new Date(result.generatedAt).toLocaleTimeString()}</span><h3>Where to fish ${escapeHtml(result.species.name)} today</h3><p>${escapeHtml(result.species.summary)}</p></div><div><span class="eyebrow">WHY THIS FISH IS HERE</span><ul>${result.species.conditionLogic.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div></div><div class="rank-list">${result.spots.slice(0,4).map((s,i)=>`<article class="rank-card"><div class="rank">${i+1}</div><div><h4>${escapeHtml(s.name)}</h4><p>${escapeHtml(s.region)} · ${escapeHtml(s.bestWindows.join(' / '))}</p><small>Best baits: ${escapeHtml(s.recommendedBaits.slice(0,3).join(', '))}</small>${s.conditionFit!=null?`<br><small>Condition Fit: ${escapeHtml(s.conditionFit)}% · Data Confidence: ${escapeHtml(s.dataConfidence)}% · Site Fit: ${escapeHtml(s.siteFit)}%</small>`:''}${currentFactorLine(s)?`<br><small>${escapeHtml(currentFactorLine(s))}</small>`:''}${s.legalGate?`<br><small>${escapeHtml(s.legalGate)}</small>`:''}</div><div class="confidence">${s.confidence}%</div></article>`).join('')}</div><div class="ray-note"><b>HOW RAY GOT THERE</b><br>${escapeHtml(result.methodology)} Recommendation Score is a planning index, not catch probability or a guarantee.</div>`;}
function renderDocuments(){const groups=state.documents.reduce((a,d)=>((a[d.category]??=[]).push(d),a),{});$('#doc-count').textContent=`${state.documents.length} cataloged resources`;$('#document-grid').innerHTML=Object.entries(groups).map(([category,docs])=>`<section class="doc-card"><span class="eyebrow">${escapeHtml(category)}</span><h3>${docs.length} resource${docs.length===1?'':'s'}</h3>${docs.map(d=>`<p><strong>${escapeHtml(d.title)}</strong><br><span class="doc-meta">${escapeHtml(d.type)} · ${escapeHtml(d.status)}</span></p>`).join('')}<button class="btn" disabled>Asset import pending</button></section>`).join('');}
function renderSources(){$('#source-grid').innerHTML=state.sources.map(s=>`<article class="source-card"><span class="badge">${escapeHtml(s.priority)}</span><h3>${escapeHtml(s.name)}</h3><p>${escapeHtml(s.purpose)}</p>${s.role?`<small><strong>RICHFISH role:</strong> ${escapeHtml(s.role)}</small>`:''}${s.caveat?`<p class="notice"><strong>Data caution:</strong> ${escapeHtml(s.caveat)}</p>`:''}${s.endpoint?`<p><a class="eyebrow" href="${escapeHtml(s.endpoint)}" target="_blank" rel="noopener">Official source →</a></p>`:''}<small>${escapeHtml(s.mode)}</small></article>`).join('');}
function nav(){const b=document.querySelector('.nav-toggle'),n=document.querySelector('.topbar nav');if(!b||!n)return;b.addEventListener('click',()=>{n.classList.toggle('open');b.setAttribute('aria-expanded',n.classList.contains('open'));});n.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>n.classList.remove('open')));}
async function boot(){try{[state.spots,state.species,state.documents,state.sources,state.conditionEngine]=await Promise.all([getJson('spots.json'),getJson('species.json'),getJson('documents.json'),getJson('sources.json'),getJsonOptional('live/condition-engine.json')]);state.selectedSpot=state.spots[0];state.selectedSpecies=state.species[0];renderConditionStrip();renderSpotList();renderSpotDetail();renderSpeciesList();selectSpecies(state.selectedSpecies.id);renderDocuments();renderSources();$('#spot-search').addEventListener('input',e=>renderSpotList(e.target.value));nav();}catch(error){console.error(error);document.body.insertAdjacentHTML('afterbegin',`<div class="load-error">Unable to load RICHFISH static data: ${escapeHtml(error.message)}</div>`);}}
boot();