const state={spots:[],species:[],documents:[],sources:[],selectedSpot:null,selectedSpecies:null};
const $=(q)=>document.querySelector(q);
const escapeHtml=(value)=>String(value??'').replace(/[&<>'"]/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const DATA_ROOT='data';

async function getJson(file){const response=await fetch(`${DATA_ROOT}/${file}`);if(!response.ok)throw new Error(`${file}: ${response.status}`);return response.json();}
function metric(label,value,note=''){return `<div class="metric"><small>${escapeHtml(label)}</small><strong>${escapeHtml(value)}</strong><span>${escapeHtml(note)}</span></div>`;}
function dataCard(label,value,note=''){return `<div class="data-card"><small>${escapeHtml(label)}</small><strong>${escapeHtml(value)}</strong><span>${escapeHtml(note)}</span></div>`;}
function scoreSpot(spot,speciesId){const match=spot.species.find(item=>item.id===speciesId);if(!match)return null;const tideScore=spot.conditions.tideTrend==='Rising'?8:4;const freshnessPenalty=Math.min(12,Math.floor((Date.now()-new Date(spot.updatedAt).getTime())/86400000));return Math.max(1,Math.min(99,match.baseScore+tideScore-freshnessPenalty));}
function recommendations(speciesId){const species=state.species.find(item=>item.id===speciesId);const spots=state.spots.map(spot=>({...spot,confidence:scoreSpot(spot,speciesId)})).filter(s=>s.confidence!==null).sort((a,b)=>b.confidence-a.confidence);return {species,generatedAt:new Date().toISOString(),methodology:'RICHFISH v0.2 static model: habitat and occurrence fit, seasonal baseline, tide trend, source freshness, access, and Richmond Ray junction logic.',spots};}

function renderConditionStrip(){const s=state.spots[0];if(!s)return;$('#condition-strip').innerHTML=[metric('Tide',s.conditions.tideTrend,'Dataset signal'),metric('Water temp',`${s.conditions.waterTempF}°F`,'Spot observation'),metric('Wind',`${s.conditions.windMph} mph`,'Prototype value'),metric('Salinity',`${s.conditions.salinityPsu} PSU`,'Estuarine signal'),metric('Depth',s.conditions.depthFt,'Fishing range')].join('');}
function renderSpotList(filter=''){const list=state.spots.filter(s=>`${s.name} ${s.region}`.toLowerCase().includes(filter.toLowerCase()));$('#spot-list').innerHTML=list.map(s=>`<button class="select-item ${state.selectedSpot?.id===s.id?'active':''}" data-spot="${s.id}"><strong>${escapeHtml(s.name)}</strong><small>${escapeHtml(s.region)}</small></button>`).join('');document.querySelectorAll('[data-spot]').forEach(b=>b.onclick=()=>selectSpot(b.dataset.spot));}
function selectSpot(id){state.selectedSpot=state.spots.find(s=>s.id===id);renderSpotList($('#spot-search').value);renderSpotDetail();}
function renderSpotDetail(){const s=state.selectedSpot;if(!s)return;$('#spot-detail').classList.remove('loading');$('#spot-detail').innerHTML=`<div class="detail-top"><div><span class="badge">● Updated ${new Date(s.updatedAt).toLocaleString()}</span><h3>${escapeHtml(s.name)}</h3><p>${escapeHtml(s.region)} · ${escapeHtml(s.city)}</p></div><div><span class="eyebrow">ACCESS</span><p>${escapeHtml(s.access)}</p></div></div><div class="detail-grid">${dataCard('Tide',s.conditions.tideTrend)}${dataCard('Water',`${s.conditions.waterTempF}°F`)}${dataCard('Salinity',`${s.conditions.salinityPsu} PSU`)}${dataCard('Wind',`${s.conditions.windMph} mph`)}${dataCard('Clarity',`${s.conditions.clarityFt} ft`)}${dataCard('Depth',s.conditions.depthFt)}${dataCard('Latitude',s.coordinates.lat)}${dataCard('Longitude',s.coordinates.lng)}</div><div class="info-layout"><div class="info-card"><small>Target fish</small><ul>${s.species.map(x=>`<li>${escapeHtml(state.species.find(sp=>sp.id===x.id)?.name||x.id)} — ${escapeHtml(x.activity)}</li>`).join('')}</ul></div><div class="info-card"><small>Recommended baits</small><ul>${s.recommendedBaits.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div><div class="info-card"><small>Recommended rigs</small><ul>${s.recommendedRigs.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div><div class="info-card"><small>Best windows</small><ul>${s.bestWindows.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div><div class="info-card"><small>Rumor report</small><ul>${s.reports.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div><div class="info-card"><small>Warnings / cautions</small><ul>${s.cautions.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div></div><div class="ray-note"><b>RAY'S CALL</b><br>“${escapeHtml(s.richmondRayNote)}”</div>`;}
function renderSpeciesList(){$('#species-list').innerHTML=state.species.map(s=>`<button class="select-item ${state.selectedSpecies?.id===s.id?'active':''}" data-species="${s.id}"><strong>${s.icon} ${escapeHtml(s.name)}</strong><small>${escapeHtml(s.scientificName)}</small></button>`).join('');document.querySelectorAll('[data-species]').forEach(b=>b.onclick=()=>selectSpecies(b.dataset.species));}
function selectSpecies(id){state.selectedSpecies=state.species.find(s=>s.id===id);renderSpeciesList();renderFinder(recommendations(id));}
function renderFinder(result){const d=$('#finder-detail');d.classList.remove('loading');d.innerHTML=`<div class="detail-top"><div><span class="badge">● Generated ${new Date(result.generatedAt).toLocaleTimeString()}</span><h3>Where to fish ${escapeHtml(result.species.name)} today</h3><p>${escapeHtml(result.species.summary)}</p></div><div><span class="eyebrow">WHY THIS FISH IS HERE</span><ul>${result.species.conditionLogic.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div></div><div class="rank-list">${result.spots.slice(0,4).map((s,i)=>`<article class="rank-card"><div class="rank">${i+1}</div><div><h4>${escapeHtml(s.name)}</h4><p>${escapeHtml(s.region)} · ${escapeHtml(s.bestWindows.join(' / '))}</p><small>Best baits: ${escapeHtml(s.recommendedBaits.slice(0,3).join(', '))}</small></div><div class="confidence">${s.confidence}%</div></article>`).join('')}</div><div class="ray-note"><b>HOW RAY GOT THERE</b><br>${escapeHtml(result.methodology)} This score is a planning aid, not a guarantee.</div>`;}
function renderDocuments(){const groups=state.documents.reduce((a,d)=>((a[d.category]??=[]).push(d),a),{});$('#doc-count').textContent=`${state.documents.length} cataloged resources`;$('#document-grid').innerHTML=Object.entries(groups).map(([category,docs])=>`<section class="doc-card"><span class="eyebrow">${escapeHtml(category)}</span><h3>${docs.length} resource${docs.length===1?'':'s'}</h3>${docs.map(d=>`<p><strong>${escapeHtml(d.title)}</strong><br><span class="doc-meta">${escapeHtml(d.type)} · ${escapeHtml(d.status)}</span></p>`).join('')}<button class="btn" disabled>Asset import pending</button></section>`).join('');}
function renderSources(){$('#source-grid').innerHTML=state.sources.map(s=>`<article class="source-card"><span class="badge">${escapeHtml(s.priority)}</span><h3>${escapeHtml(s.name)}</h3><p>${escapeHtml(s.purpose)}</p><small>${escapeHtml(s.mode)}</small></article>`).join('');}
function nav(){const b=document.querySelector('.nav-toggle'),n=document.querySelector('.topbar nav');if(!b||!n)return;b.addEventListener('click',()=>{n.classList.toggle('open');b.setAttribute('aria-expanded',n.classList.contains('open'));});n.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>n.classList.remove('open')));}
async function boot(){try{[state.spots,state.species,state.documents,state.sources]=await Promise.all(['spots.json','species.json','documents.json','sources.json'].map(getJson));state.selectedSpot=state.spots[0];state.selectedSpecies=state.species[0];renderConditionStrip();renderSpotList();renderSpotDetail();renderSpeciesList();selectSpecies(state.selectedSpecies.id);renderDocuments();renderSources();$('#spot-search').addEventListener('input',e=>renderSpotList(e.target.value));nav();}catch(error){console.error(error);document.body.insertAdjacentHTML('afterbegin',`<div class="load-error">Unable to load RICHFISH static data: ${escapeHtml(error.message)}</div>`);}}
boot();