/* LEGZ & JINX — 9:00 PM PT NEXT-DAY MASTER PUBLICATION
   Target publication date: September 9, 2026.
   FULL HARD REPLACEMENT. DATA ONLY; approved presentation remains locked in ljapp.js + ljqc.css.
   Prior-day audit is stored separately in ljrecapdata.js. */
(() => {
  const D=window.LJ_DATA; if(!D) return;
  const WATCH="WATCH — exact current market not independently verified after multi-source sweep";
  const q=(time,away,home,market,winner,conf,hot=[],sns1=[],sns2=[],normal=[],demon=[],foot="")=>({time,away,home,market,winner,conf,hot,sns1,sns2,normal,demon,foot});
  const row=(sport,name,pred,price,conf,quality="★★★★☆",risk="🔥")=>[sport,name,pred,price,conf,quality,risk];
  const nav=[["MLB","⚾","MLB.html"],["NFL","🏈","NFL.html"],["NBA","🏀","NBA.html"],["WNBA","🏀","WNBA.html"],["NHL","🏒","NHL.html"],["FIBA MEN","🌍🏀","FIBA_Men.html"],["FIBA WOMEN","🌍🏀","FIBA_Women.html"],["NCAA FOOTBALL","🏈","NCAA_Football.html"],["NCAA BASKETBALL","🏀","NCAA_Basketball.html"],["UFC","🥊","UFC.html"],["BOXING","🥊","Boxing.html"],["TENNIS","🎾","Tennis.html"]];
  D.updated="Updated Sep 8, 2026 • 9:00 PM PT — SEP 9 MASTER PUBLICATION"; D.nav=nav;
  const status=(icon,title,state,detail,next="")=>({icon,title,meta:`${title} • ${state} • SEP 9 MASTER`,kicker:title,description:detail,chips:[[state,"purple"],["SEP 9 HARD REPLACEMENT","gold"]],hotTop:[],winners:[],twenty:[],twentyNote:next||detail,qcTitle:`${title} — ${state}`,qcs:[]});

  const MLB={icon:"⚾",title:"MLB",meta:"MLB • WEDNESDAY SEPTEMBER 9, 2026 • MASTER",kicker:"MLB DAILY PREDICTIONS",
    description:"All 15 Wednesday MLB games receive Per-Game Quickies. StatsHawk verifies the full slate and most probable pitchers. Toronto, Atlanta and Arizona still lack a verified starter in the 9 PM PT feed; those pitcher-dependent sections remain WATCH. Exact Wednesday player props are not broadly exposed at master time, so no Tuesday threshold is reused.",
    chips:[["15 GAME QCs","green"],["SEP 9 ONLY","gold"],["NO STALE PROP REUSE","purple"]],
    hotTop:[
      ["Yoshinobu Yamamoto","6+ strikeouts ACTIVATION TARGET","69%","Late home matchup vs Cincinnati; exact Wednesday threshold required before activation."],
      ["Hunter Brown","5+ strikeouts ACTIVATION TARGET","66%","Philadelphia matchup is difficult but Brown remains a strong workload/K-ceiling channel; exact line required."],
      ["Cristopher Sánchez","5+ strikeouts ACTIVATION TARGET","65%","Home start vs Houston; prefer lower milestone to an aggressive high threshold."],
      ["Kevin Gausman","5+ strikeouts ACTIVATION TARGET","64%","Milwaukee contact quality keeps this Normal until exact market opens."],
      ["Will Warren","5+ strikeouts ACTIVATION TARGET","63%","Colorado matchup at Yankee Stadium; exact line and weather recheck required."],
      ["Shane Baz","5+ strikeouts ACTIVATION TARGET","61%","Cleveland contact profile caps confidence despite swing-and-miss ceiling."],
      ["Jaxon Smith-Njigba","Over 81.5 receiving yards -114","60%","NFL night-game market; included on NFL board, not MLB tickets."],
      ["Rhamondre Stevenson","Over 55.5 rushing yards -114","62%","NFL workload upgrade after TreVeyon Henderson was ruled out." ]
    ],
    winners:[
      ["MIN @ DET","Tigers lean","55%","Montero vs Matthews; price WATCH at master sweep."],
      ["TOR @ ATH","Blue Jays ML -170 snapshot","63%","Toronto is a road favorite; Toronto starter still unverified, so confidence stays capped."],
      ["STL @ SF","Giants lean","54%","Tidwell-Pallante matchup; exact side price WATCH."],
      ["TEX @ SEA","Mariners ML -124 snapshot","58%","Kade Anderson vs Cody Bradford with Seattle modestly favored."],
      ["WSH @ SD","Padres ML -195 snapshot","67%","San Diego is the strongest verified MLB side price but payout efficiency is poor."],
      ["CLE @ BAL","Orioles lean","55%","Baz-Griffin; exact side price not cleanly exposed at master sweep."],
      ["HOU @ PHI","Phillies ML -154 snapshot","59%","Current market and projection favor Philadelphia despite Houston's Sep 8 win."],
      ["NYM @ MIA","Marlins ML -120 snapshot","56%","Current numberFire/FanDuel board slightly favors Miami."],
      ["LAA @ BOS","Red Sox ML -210 snapshot","66%","Boston remains a substantial home favorite; expensive price."],
      ["COL @ NYY","Yankees ML -253 snapshot","72%","Largest verified MLB team edge on the current board; poor multiplier efficiency."],
      ["TB @ ATL","WATCH","—","Atlanta probable starter not verified; no fabricated side."],
      ["ARI @ KC","WATCH","—","Arizona probable starter not verified; no fabricated side."],
      ["CHC @ MIL","Brewers lean","57%","Gausman-Henderson matchup; exact side price WATCH."],
      ["PIT @ CWS","Pirates lean","58%","Pittsburgh won 9-3 Tuesday; Bachar-Martin matchup still requires price confirmation."],
      ["CIN @ LAD","Dodgers lean","67%","Yamamoto gives Los Angeles the preferred starter channel; exact side price WATCH."]
    ],
    twenty:[
      row("MLB","Yoshinobu Yamamoto","6+ strikeouts","TARGET","69%"),row("MLB","Hunter Brown","5+ strikeouts","TARGET","66%"),row("MLB","Cristopher Sánchez","5+ strikeouts","TARGET","65%"),row("MLB","Kevin Gausman","5+ strikeouts","TARGET","64%"),row("MLB","Will Warren","5+ strikeouts","TARGET","63%"),row("MLB","Shane Baz","5+ strikeouts","TARGET","61%"),row("MLB","Walker Buehler","5+ strikeouts","TARGET","57%"),row("MLB","Yankees","Moneyline","-253 snapshot","72%"),row("MLB","Padres","Moneyline","-195 snapshot","67%"),row("MLB","Phillies","Moneyline","-154 snapshot","59%")
    ],
    twentyNote:"TARGET means analytical activation target, not an executable player prop. Wednesday player thresholds must be verified at the 9:00 AM refresh before appearing in tickets. No opposite sides of the same exact threshold are published simultaneously.",
    qcTitle:"MLB — SEPTEMBER 9 PER-GAME QUICKIES",
    qcs:[
      q("1:10 ET • 10:10 AM PT","MIN","DET","Matthews vs Montero • side price WATCH","Tigers lean","55%",["Keider Montero 4+ K TARGET • 56%"],[WATCH],[WATCH],[WATCH],[WATCH],"Early game. Lineups and exact props are morning gates."),
      q("3:05 ET • 12:05 PM PT","TOR","ATH","TOR -170 / ATH +163 snapshot • Toronto starter WATCH","Blue Jays ML","63%",[WATCH],[WATCH],[WATCH],[WATCH],[WATCH],"Toronto starter is not verified in StatsHawk at master sweep; do not publish pitcher props."),
      q("3:45 ET • 12:45 PM PT","STL","SF","Pallante vs Tidwell • side price WATCH","Giants lean","54%",["Blade Tidwell 4+ K TARGET • 56%"],[WATCH],[WATCH],[WATCH],[WATCH],"Exact market pending."),
      q("4:10 ET • 1:10 PM PT","TEX","SEA","SEA -124 / TEX +106 • total 7.5 snapshot","Mariners ML","58%",["Kade Anderson 5+ K TARGET • 59%"],[WATCH],[WATCH],["Kade Anderson 5+ K TARGET • 59%"],[WATCH],"Starter matchup verified; player line remains target-only until exact threshold opens."),
      q("4:10 ET • 1:10 PM PT","WSH","SD","SD -195 / WSH +164 • total 8.5 snapshot","Padres ML","67%",["Walker Buehler 5+ K TARGET • 57%"],[WATCH],[WATCH],["Buehler 5+ K TARGET • 57%"],[WATCH],"Price is expensive; player prop requires exact market."),
      q("6:35 ET • 3:35 PM PT","CLE","BAL","Griffin vs Baz • exact side price WATCH","Orioles lean","55%",["Shane Baz 5+ K TARGET • 61%"],[WATCH],[WATCH],["Baz 5+ K TARGET • 61%"],[WATCH],"Do not recycle Sep 8 Brandon Young/Bibee lines."),
      q("6:40 ET • 3:40 PM PT","HOU","PHI","PHI -154 / HOU +130 snapshot • total around 8","Phillies ML","59%",["Hunter Brown 5+ K TARGET • 66%","Cristopher Sánchez 5+ K TARGET • 65%"],[WATCH],[WATCH],["Brown 5+ K TARGET • 66%","Sánchez 5+ K TARGET • 65%"],[WATCH],"Current team market verified; exact player props were not broadly exposed at master sweep."),
      q("6:40 ET • 3:40 PM PT","NYM","MIA","MIA -120 / NYM +102 snapshot","Marlins ML","56%",["Janson Junk 4+ K TARGET • 55%"],[WATCH],[WATCH],[WATCH],[WATCH],"Marlins slight current favorite; player props pending."),
      q("6:45 ET • 3:45 PM PT","LAA","BOS","BOS -210 / LAA +176 snapshot","Red Sox ML","66%",["Jake Bennett 4+ K TARGET • 55%"],[WATCH],[WATCH],[WATCH],[WATCH],"Expensive side; avoid forcing it into parlays solely for hit probability."),
      q("7:05 ET • 4:05 PM PT","COL","NYY","NYY -253 / COL +200 • total 9 snapshot","Yankees ML","72%",["Will Warren 5+ K TARGET • 63%"],[WATCH],[WATCH],["Warren 5+ K TARGET • 63%"],[WATCH],"Judge and all batter props remain lineup/market gated."),
      q("7:15 ET • 4:15 PM PT","TB","ATL","Griffin Jax vs ATL starter unverified • full side WATCH","WATCH","—",[WATCH],[WATCH],[WATCH],[WATCH],[WATCH],"Atlanta probable pitcher missing in current feed; no side or pitcher prop is manufactured."),
      q("7:40 ET • 4:40 PM PT","ARI","KC","ARI starter unverified vs Daniel Lynch IV • full side WATCH","WATCH","—",[WATCH],[WATCH],[WATCH],[WATCH],[WATCH],"Arizona probable pitcher missing in current feed."),
      q("7:40 ET • 4:40 PM PT","CHC","MIL","Gausman vs Logan Henderson • side price WATCH","Brewers lean","57%",["Kevin Gausman 5+ K TARGET • 64%"],[WATCH],[WATCH],["Gausman 5+ K TARGET • 64%"],[WATCH],"Exact threshold required; no Sep 8 Misiorowski/Peterson line is reused."),
      q("7:40 ET • 4:40 PM PT","PIT","CWS","Bachar vs Davis Martin • side price WATCH","Pirates lean","58%",["Davis Martin / Lake Bachar K markets WATCH"],[WATCH],[WATCH],[WATCH],[WATCH],"Tuesday result informs context only; Wednesday exact props must stand on their own."),
      q("10:10 ET • 7:10 PM PT","CIN","LAD","Lowder vs Yamamoto • exact side price WATCH","Dodgers lean","67%",["Yoshinobu Yamamoto 6+ K TARGET • 69%"],[WATCH],[WATCH],["Yamamoto 6+ K TARGET • 69%"],[WATCH],"No Sep 8 Skubal/Lodolo line survives the hard replacement.")
    ]};

  const NFL={icon:"🏈",title:"NFL",meta:"NFL • WEDNESDAY SEPTEMBER 9, 2026 • MASTER",kicker:"NFL DAILY PREDICTIONS",
    description:"New England at Seattle is the verified September 9 NFL game: 8:20 PM ET / 5:20 PM PT at Lumen Field. TreVeyon Henderson is OUT, materially increasing Rhamondre Stevenson's expected rushing workload. Current FanDuel markets are incorporated where independently exposed.",chips:[["1 GAME QC","green"],["5:20 PM PT","gold"],["INJURY-ADJUSTED","purple"]],
    hotTop:[["Rhamondre Stevenson","Over 55.5 rushing yards -114","62%","Henderson OUT raises early-down and total carry expectation."],["Jaxon Smith-Njigba","Over 81.5 receiving yards -114","60%","Primary Seattle receiving channel."],["A.J. Brown","Over 62.5 receiving yards -114","58%","Volume-based New England receiving angle."],["Drake Maye","Over 234.5 passing yards -114","56%","Game script can create volume if New England trails."],["Sam Darnold","2+ passing TD +114","48%","Demon-only ceiling play."],["Jadarian Price","Anytime TD +135","50%","Demon-only touchdown variance."]],
    winners:[["Patriots @ Seahawks","Seahawks ML -170 snapshot","61%","Seattle -3.5 is playable only at lower confidence; home side remains preferred."],["Patriots @ Seahawks","Under 44.5 -110","55%","Secondary total lean, not stronger than Stevenson workload market."]],
    twenty:[row("NFL","Rhamondre Stevenson","O55.5 rushing yards","-114 FD","62%"),row("NFL","Jaxon Smith-Njigba","O81.5 receiving yards","-114 FD","60%"),row("NFL","A.J. Brown","O62.5 receiving yards","-114 FD","58%"),row("NFL","Drake Maye","O234.5 passing yards","-114 FD","56%"),row("NFL","Seahawks","Moneyline","-170 snapshot","61%"),row("NFL","Seahawks","-3.5 spread","-104 FD","55%"),row("NFL","Game","Under 44.5","-110 FD","55%"),row("NFL","Jadarian Price","Anytime TD","+135 FD","50%","★★★☆☆","🔥🔥"),row("NFL","Sam Darnold","2+ pass TD","+114 FD","48%","★★★☆☆","🔥🔥🔥")],
    twentyNote:"Henderson's OUT designation is a material role change and drives the Stevenson upgrade. Late inactives, weather and line movement require morning/noon recheck.",qcTitle:"NFL — SEPTEMBER 9 PER-GAME QUICKIE",
    qcs:[q("8:20 ET • 5:20 PM PT","NEW ENGLAND","SEATTLE","SEA -3.5 -104 • ML -170 snapshot • total 44.5","Seahawks ML","61%",["Stevenson O55.5 rush -114 • 62%","JSN O81.5 rec -114 • 60%","A.J. Brown O62.5 rec -114 • 58%","Maye O234.5 pass -114 • 56%"],["Stevenson O55.5 rush -114 • 62%"],["JSN O81.5 rec -114 • 60%"],["Stevenson O55.5 + JSN O81.5 • current exact legs"],["Price anytime TD +135","Darnold 2+ pass TD +114"],"Henderson OUT. Seattle S Ty Okada OUT; other questionable designations require final inactives sweep.")]};

  const FIBA={icon:"🌍🏀",title:"FIBA WOMEN",meta:"FIBA WOMEN • WEDNESDAY SEPTEMBER 9, 2026 • MASTER",kicker:"FIBA WOMEN'S WORLD CUP",
    description:"Wednesday's next qualification games are Puerto Rico vs China and Italy vs Australia. Official FIBA preview data strongly supports China's size/recent head-to-head edge and Australia's paint/depth advantage. Exact participant props and team prices were not independently exposed at master time, so they remain WATCH.",chips:[["2 QUALIFICATION QCs","green"],["NEXT-GAME-ONLY","gold"],["OFFICIAL FIBA MATCHUPS","purple"]],
    hotTop:[["Xu Han","Points + rebounds market WATCH","—","China's leading interior focal point with three tournament double-doubles; exact threshold required."],["China","Match winner lean","72%","China won the recent head-to-head meetings 80-58 and 95-60."],["Australia","Match winner lean","67%","Australia's paint production is a major structural advantage against Italy."],["Cecilia Zandalasini","Points market WATCH","—","Italy scoring channel; exact line required."]],
    winners:[["Puerto Rico vs China","China","72%","Strong size/interior and recent H2H edge."],["Italy vs Australia","Australia","67%","Australia's interior depth rates higher; Italy's poor three-point tournament rate adds risk."]],
    twenty:[row("FIBA WOMEN","China","Match winner","WATCH exact price","72%"),row("FIBA WOMEN","Australia","Match winner","WATCH exact price","67%"),row("FIBA WOMEN","Xu Han","Points + rebounds","WATCH","—"),row("FIBA WOMEN","Cecilia Zandalasini","Points","WATCH","—")],
    twentyNote:"No player threshold is invented. Team winner leans are predictions until an exact current price is verified.",qcTitle:"FIBA WOMEN — SEPTEMBER 9 NEXT-GAME QCs",
    qcs:[q("17:45 Berlin • 8:45 AM PT","PUERTO RICO","CHINA","Exact current team/player market WATCH","China","72%",["Xu Han P+R — WATCH exact threshold"],[WATCH],[WATCH],[WATCH],[WATCH],"Winner advances to face France. China owns strong recent H2H results."),q("20:45 Berlin • 11:45 AM PT","ITALY","AUSTRALIA","Exact current team/player market WATCH","Australia","67%",["Zandalasini points — WATCH","Australia paint/rebounds — WATCH exact market"],[WATCH],[WATCH],[WATCH],[WATCH],"Winner advances to face Spain; exact player lines remain unverified.")]};

  const Tennis={icon:"🎾",title:"TENNIS",meta:"TENNIS • US OPEN • WEDNESDAY SEPTEMBER 9, 2026 • MASTER",kicker:"US OPEN QUARTERFINALS",
    description:"Wednesday quarterfinal coverage uses official order/session language. No artificial start time is assigned to FOLLOWS matches. Current winner prices are included only where independently exposed.",chips:[["4 QF QCs","green"],["OFFICIAL OOP LANGUAGE","gold"],["NO INVENTED TIMES","purple"]],
    hotTop:[["Elena Rybakina","Match winner -280 snapshot","71%","Rybakina leads Zheng 4-1 H2H and entered the quarterfinal without dropping a set."],["Coco Gauff","Match winner lean","62%","Gauff is 5-0 head-to-head against Mirra Andreeva; exact current winner price WATCH."],["Karen Khachanov","Match winner 1.60 decimal snapshot","64%","Blockx carries a rib-injury concern and less five-set experience."],["Alexander Zverev","Match winner 1.08 decimal snapshot","86%","Extremely expensive favorite; price efficiency is poor."],["Alexander Zverev","Win 3-0 1.80 decimal","52%","Demon-only alternative to the short ML."]],
    winners:[["Rybakina vs Zheng","Rybakina","71%","FIRST MATCH day session."],["Gauff vs Andreeva","Gauff","62%","FOLLOWS Rybakina-Zheng."],["Blockx vs Khachanov","Khachanov","64%","NOT BEFORE 2:00 PM ET."],["Van de Zandschulp vs Zverev","Zverev","86%","NIGHT SESSION 7:30 PM ET."]],
    twenty:[row("TENNIS","Elena Rybakina","Match winner","-280 snapshot","71%"),row("TENNIS","Coco Gauff","Match winner","WATCH exact price","62%"),row("TENNIS","Karen Khachanov","Match winner","1.60 decimal","64%"),row("TENNIS","Alexander Zverev","Match winner","1.08 decimal","86%"),row("TENNIS","Alexander Zverev","Win 3-0","1.80 decimal","52%","★★★☆☆","🔥🔥🔥")],
    twentyNote:"Order language follows official US Open scheduling. Injury/status is a morning kill switch for Blockx; exact Gauff price must be refreshed.",qcTitle:"TENNIS — US OPEN SEPTEMBER 9 QFs",
    qcs:[q("DAY SESSION • FIRST MATCH • 11:30 AM ET","QINWEN ZHENG","ELENA RYBAKINA","Rybakina -280 / Zheng +235 snapshot","Rybakina","71%",["Rybakina ML -280 • 71%"],["Rybakina ML • 71%"],[WATCH],["Rybakina ML • 71%"],[WATCH],"Rybakina 4-1 H2H edge."),q("FOLLOWS RYBAKINA-ZHENG","MIRRA ANDREEVA","COCO GAUFF","Exact current price WATCH","Gauff","62%",["Gauff ML — WATCH exact price"],[WATCH],[WATCH],[WATCH],[WATCH],"Gauff owns a 5-0 H2H edge; do not invent a follows start time."),q("NOT BEFORE 2:00 PM ET","ALEXANDER BLOCKX","KAREN KHACHANOV","Khachanov 1.60 / Blockx 2.20 snapshot","Khachanov","64%",["Khachanov ML 1.60 • 64%"],[WATCH],[WATCH],["Khachanov ML • 64%"],[WATCH],"Blockx rib status requires morning confirmation."),q("NIGHT SESSION • 7:30 PM ET","BOTIC VAN DE ZANDSCHULP","ALEXANDER ZVEREV","Zverev 1.08 / Botic 6.50 snapshot","Zverev","86%",["Zverev ML 1.08 • 86%","Zverev 3-0 1.80 • 52%"],["Zverev ML • 86%"],[WATCH],["Zverev ML • 86%"],["Zverev 3-0 1.80 • 52%"],"Heavy favorite; straight-sets is Demon-tier rather than pretending the ML offers useful payout.")]};

  const UFC={icon:"🥊",title:"UFC",meta:"UFC • NEXT ANNOUNCED EVENT • SEP 12, 2026",kicker:"UFC EVENT PREDICTIONS",description:"Noche UFC is officially scheduled for Saturday, September 12 at Desert Diamond Arena in Glendale. Current official bout prices are populated where verified; exact method/round props remain WATCH.",chips:[["NEXT EVENT SEP 12","green"],["EVENT QC LIVE","gold"]],hotTop:[["Jean Silva","Match winner -400","80%","Verified current favorite over Jose Miguel Delgado."],["Joseph Morales","Match winner -130","57%","Current favorite over Brandon Moreno; moderate edge only."]],winners:[["Jean Silva vs Jose Miguel Delgado","Jean Silva -400","80%","High win probability / poor price efficiency."],["Brandon Moreno vs Joseph Morales","Joseph Morales -130","57%","Closer market; Normal only."]],twenty:[row("UFC","Jean Silva","Fight winner","-400","80%"),row("UFC","Joseph Morales","Fight winner","-130","57%")],twentyNote:"Method/round and remaining bout props are added only after exact verification.",qcTitle:"UFC — NOCHE UFC • SEPTEMBER 12",qcs:[q("SEP 12 • MAIN CARD 5:00 PM ET","NOCHE UFC","GLENDALE, AZ","Verified winner markets available on selected bouts","EVENT QC ACTIVE","—",["Jean Silva -400 • 80%","Joseph Morales -130 • 57%"],[WATCH],[WATCH],["Silva ML • 80%","Morales ML • 57%"],[WATCH],"Event-level QC remains active ahead of fight day; morning/event-day sweeps add verified props.")]};

  const Boxing={icon:"🥊",title:"BOXING",meta:"BOXING • NEXT ANNOUNCED EVENT • SEP 12, 2026",kicker:"BOXING EVENT PREDICTIONS",description:"Ryan Garcia vs Conor Benn remains officially scheduled for September 12 at T-Mobile Arena. The Opetaia-Mikaelian co-main is under a fresh legal/contract dispute and is therefore STATUS WATCH rather than treated as certain. Exact Garcia-Benn odds were not independently verified in this master sweep.",chips:[["NEXT EVENT SEP 12","green"],["CO-MAIN STATUS WATCH","gold"]],hotTop:[["Garcia vs Benn","Winner/props WATCH","—","Official main event remains scheduled; exact current odds required."],["Opetaia vs Mikaelian","STATUS WATCH","—","Fresh cease-and-desist/contract dispute creates event-risk uncertainty."]],winners:[["Ryan Garcia vs Conor Benn","WATCH","—","No fabricated winner price."],["Jai Opetaia vs Noel Mikaelian","STATUS WATCH","—","Do not publish as settled card component until dispute status is clarified."]],twenty:[],twentyNote:"The event QC stays published immediately, but disputed or unverified markets are explicitly gated.",qcTitle:"BOXING — GARCIA VS BENN • SEPTEMBER 12",qcs:[q("SEP 12 • MAIN CARD 8:00 PM ET / 5:00 PM PT","RYAN GARCIA","CONOR BENN","Exact winner/prop market WATCH","WATCH","—",[WATCH],[WATCH],[WATCH],[WATCH],[WATCH],"Official main event. Co-main Opetaia-Mikaelian carries a current legal/contract status warning.")]};

  const NBA=status("🏀","NBA","SEASON START / OFFSEASON STATUS","No September 9 NBA regular-season game is published. Page remains in explicit season-start/offseason state.");
  const WNBA=status("🏀","WNBA","NEXT ANNOUNCED EVENT","No September 9 monitored WNBA club game is verified for the active publication. Next announced event remains gated to a fresh schedule/market sweep.");
  const NHL=status("🏒","NHL","SEASON START / OFFSEASON STATUS","No September 9 NHL regular-season game is published. Page remains in explicit season-start/offseason state.");
  const FIBAM=status("🌍🏀","FIBA MEN","NEXT ANNOUNCED EVENT","No monitored senior FIBA Men event is verified for September 9; page remains next-announced-event gated.");
  const NCAA=status("🏈","NCAA FOOTBALL","NEXT ANNOUNCED EVENT","No September 9 FBS game was confirmed in the master schedule sweep. Page advances to the next announced college-football slate; no prior Monday/Tuesday props survive.","Every next listed game must receive kickoff time and a fresh multi-source player-prop sweep.");
  const NCAAB=status("🏀","NCAA BASKETBALL","SEASON START / OFFSEASON STATUS","No September 9 NCAA basketball game is published; page remains explicit offseason/season-start status.");
  D.sports={MLB,NFL,NBA,WNBA,NHL,FIBA_Men:FIBAM,FIBA_Women:FIBA,NCAA_Football:NCAA,NCAA_Basketball:NCAAB,UFC,Boxing,Tennis};
})();