/* LEGZ & JINX DAILY DATA
   DAILY REFRESH FILE: update odds, props, confidence, status and schedules here.
   DO NOT change QC presentation/layout during a prediction refresh. */
window.LJ_DATA = (() => {
  const WATCH = "WATCH — no independently verified current player market";
  const CLOSED = "CLOSED / LIVE — game already started; no new action and no chasing";
  const nav = [
    ["MLB","⚾","MLB.html"],["NFL","🏈","NFL.html"],["NBA","🏀","NBA.html"],["WNBA","🏀","WNBA.html"],["NHL","🏒","NHL.html"],
    ["FIBA MEN","🌍🏀","FIBA_Men.html"],["FIBA WOMEN","🌍🏀","FIBA_Women.html"],["NCAA FOOTBALL","🏈","NCAA_Football.html"],
    ["NCAA BASKETBALL","🏀","NCAA_Basketball.html"],["UFC","🥊","UFC.html"],["BOXING","🥊","Boxing.html"]
  ];
  const mlb20 = [
    ["MLB","Kade Anderson","Over 5.5 strikeouts","-105","69%","★★★★☆","🔥🔥"],
    ["MLB","Jake Bauers","Over 0.5 hits","-156","68%","★★★★☆","🔥"],
    ["MLB","Brandon Young","Under 17.5 outs","-125","65%","★★★★☆","🔥"],
    ["MLB","Yordan Alvarez","Over 0.5 walks","-117","64%","★★★★☆","🔥"],
    ["MLB","Shane McClanahan","Under 4.5 strikeouts","+105","61%","★★★★☆","🔥🔥"],
    ["MLB","Bobby Witt Jr.","Over 1.5 total bases","-104","59%","★★★★☆","🔥🔥"],
    ["MLB","Heriberto Hernandez","Over 1.5 total bases","+130","58%","★★★★☆","🔥🔥"],
    ["MLB","Lawrence Butler","Over 0.5 singles","+133","56%","★★★★☆","🔥🔥"],
    ["MLB","Pete Crow-Armstrong","Over 1.5 total bases","+117","55%","★★★★☆","🔥🔥"],
    ["MLB","Seiya Suzuki","Over 1.5 total bases","+165","49%","★★★★☆","🔥🔥🔥"],
    ["MLB","Jackson Chourio","Over 0.5 RBI","+152","48%","★★★★☆","🔥🔥🔥"],
    ["MLB","Salvador Perez","Over 0.5 RBI","+165","46%","★★★★☆","🔥🔥🔥"],
    ["MLB","Alex Bregman","Over 0.5 RBI","+200","43%","★★★★☆","🔥🔥🔥"],
    ["MLB","Michael Busch","Over 0.5 RBI","+200","42%","★★★★☆","🔥🔥🔥"],
    ["MLB","Luis Robert Jr.","Over 1.5 total bases","+175","42%","★★★☆☆","🔥🔥🔥"],
    ["MLB","Ian Happ","Over 0.5 RBI","+210","40%","★★★☆☆","🔥🔥🔥"],
    ["MLB","Wyatt Langford","Over 0.5 RBI","+226","39%","★★★☆☆","🔥🔥🔥"],
    ["MLB","Gunnar Henderson","Over 0.5 RBI","+233","38%","★★★☆☆","🔥🔥🔥"],
    ["MLB","Brice Turang","Over 0.5 RBI","+231","38%","★★★☆☆","🔥🔥🔥"],
    ["MLB","Miguel Vargas","Over 0.5 RBI","+195","37%","★★★☆☆","🔥🔥🔥"]
  ];
  const empty20 = [];
  const q = (time,away,home,market,winner,conf,hot,sns1,sns2,normal,demon,foot="") => ({time,away,home,market,winner,conf,hot,sns1,sns2,normal,demon,foot});
  const w = x => [x];
  const watchTickets = () => [WATCH];

  const sports = {
    MLB:{
      icon:"⚾",meta:"MLB DAILY • SEPTEMBER 3, 2026 • LIVE SLATE",kicker:"MLB DAILY QUICKIE",title:"MLB PREDICTIONS",
      description:"Today’s September 3 slate is published in the approved horizontal Per-Game Quickie Card format. Current odds and player markets may refresh during the day; the QC presentation does not change.",
      chips:[["CURRENT SLATE","green"],["JINX CONFIDENCE","purple"],["LAYOUT LOCKED","gold"]],
      hotTop:[
        ["Kade Anderson","Over 5.5 K • -105","69%","Best K-rate matchup of his first three starts; current projection is above the posted line."],
        ["Jake Bauers","Over 0.5 Hits • -156","68%","Contact-first floor market; strong platoon and recent-contact setup."],
        ["Brandon Young","Under 17.5 Outs • -125","65%","Shorter expected leash and tougher Boston run environment."],
        ["Yordan Alvarez","Over 0.5 Walks • -117","64%","Elite walk profile and a matchup that gives pitchers incentive to work around him."],
        ["Shane McClanahan","Under 4.5 K • +105","61%","Pitch-count/leash risk suppresses his strikeout ceiling."],
        ["Bobby Witt Jr.","Over 1.5 Total Bases • -104","59%","High-end contact skill plus a favorable run-scoring environment."],
        ["Heriberto Hernandez","Over 1.5 Total Bases • +130","58%","Power projection and favorable Kauffman hitting conditions."],
        ["Lawrence Butler","Over 0.5 Singles • +133","56%","Recent on-base form plus favorable pitch-mix path to a single."]
      ],
      winners:[
        ["SF @ PIT","Pirates pregame lean","60%","CLOSED/LIVE"],["TOR @ CLE","Blue Jays pregame lean","54%","CLOSED/LIVE"],
        ["CWS @ HOU","Astros ML","65%","HOU around -159"],["BOS @ BAL","Red Sox ML lean","58%","BOS around -125"],
        ["MIL @ CHC","Brewers ML lean","55%","MIL around -115"],["MIA @ KC","PASS / Royals hairline lean","51%","KC around -116"],
        ["TB @ TEX","Rays ML lean","56%","TB around -126"],["ATH @ SEA","Mariners ML","66%","SEA around -215"],
        ["STL @ LAD","Dodgers ML","73%","LAD around -286"]
      ],
      twenty:mlb20,
      twentyNote:"20 unique MLB players. Ranked by L&J hit-confidence at the displayed threshold, not by payout. Prices are market snapshots and must be rechecked before use.",
      qcTitle:"PER-GAME QUICKIES — SEPTEMBER 3 SLATE",
      qcs:[
        q("12:35 ET • STARTED","SF","PIT","Pregame approx. SF +147 / PIT -160 • O/U 9","Pirates pregame lean","60%",w(CLOSED),w(CLOSED),w(CLOSED),w(CLOSED),w(CLOSED),"Started games remain visible for audit continuity; do not chase live movement."),
        q("1:10 ET • STARTED","TOR","CLE","Pregame near pick'em • O/U 7.5","Blue Jays pregame lean","54%",w(CLOSED),w(CLOSED),w(CLOSED),w(CLOSED),w(CLOSED),"Pregame QC closed once first pitch occurred."),
        q("2:10 ET","CWS","HOU","HOU ~-159 / CWS +140 • O/U 8.5","Astros ML","65%",["Yordan Alvarez O0.5 BB (-117) • 64%","Miguel Vargas O0.5 RBI (+195) • 37%"],["Alvarez O0.5 BB • 64%"],["Alvarez O0.5 BB • 64%","Vargas O0.5 RBI • 37%"],["Alvarez O0.5 BB • 64%"],["Vargas O0.5 RBI (+195) • 37%"],"Kill switch: if Alvarez is not in the confirmed lineup, remove every Alvarez construction."),
        q("7:15 ET","MIL","CHC","MIL ~-115 / CHC -102 • O/U 8.5","Brewers ML lean","55%",["Jake Bauers O0.5 H (-156) • 68%","Pete Crow-Armstrong O1.5 TB (+117) • 55%","Seiya Suzuki O1.5 TB (+165) • 49%","Jackson Chourio O0.5 RBI (+152) • 48%","Alex Bregman O0.5 RBI (+200) • 43%","Michael Busch O0.5 RBI (+200) • 42%"],["Bauers O0.5 H • 68%","PCA O1.5 TB • 55%"],["Bauers O0.5 H • 68%","Chourio O0.5 RBI • 48%","PCA O1.5 TB • 55%"],["Bauers O0.5 H • 68%","PCA O1.5 TB • 55%","Suzuki O1.5 TB • 49%"],["Bregman O0.5 RBI (+200) • 43%","Busch O0.5 RBI (+200) • 42%","Turang O0.5 RBI (+231) • 38%"],"Warm Wrigley run environment raises ceiling but also increases variance across RBI/TB markets."),
        q("7:15 ET","BOS","BAL","BOS ~-125 / BAL +108 • O/U 8.5","Red Sox ML lean","58%",["Brandon Young U17.5 Outs (-125) • 65%","Luis Robert Jr. O1.5 TB (+175) • 42%","Gunnar Henderson O0.5 RBI (+233) • 38%"],["Young U17.5 Outs • 65%"],["Young U17.5 Outs • 65%","Robert O1.5 TB • 42%"],["Young U17.5 Outs • 65%","Robert O1.5 TB • 42%"],["Henderson O0.5 RBI (+233) • 38%","Robert O0.5 RBI (+226) • 39%"],"Young outs is the floor expression; RBI markets are ceiling plays, not SNS legs."),
        q("7:40 ET","MIA","KC","KC ~-116 / MIA -102 • O/U 9","PASS / KC hairline lean","51%",["Bobby Witt Jr. O1.5 TB (-104) • 59%","Heriberto Hernandez O1.5 TB (+130) • 58%","Salvador Perez O0.5 RBI (+165) • 46%"],["Witt O1.5 TB • 59%"],["Witt O1.5 TB • 59%","Hernandez O1.5 TB • 58%"],["Witt O1.5 TB • 59%","Hernandez O1.5 TB • 58%"],["Perez O0.5 RBI (+165) • 46%","Hernandez O0.5 RBI (+155) • 45%"],"Game side is too close for a strong ML stamp; player markets are cleaner than the side."),
        q("8:05 ET","TB","TEX","TB ~-126 / TEX +110 • O/U 7.5–8","Rays ML lean","56%",["Shane McClanahan U4.5 K (+105) • 61%","Wyatt Langford O0.5 RBI (+226) • 39%","Cedric Mullins O0.5 RBI (+230) • 38%"],["McClanahan U4.5 K • 61%"],["McClanahan U4.5 K • 61%",WATCH],["McClanahan U4.5 K • 61%","Langford O0.5 RBI • 39%"],["Langford O0.5 RBI (+226) • 39%","Mullins O0.5 RBI (+230) • 38%"],"McClanahan workload is the core matchup channel; do not upgrade low-hit RBI props into SNS."),
        q("9:40 ET","ATH","SEA","SEA ~-215 / ATH +181 • O/U 7.5","Mariners ML","66%",["Kade Anderson O5.5 K (-105) • 69%","Lawrence Butler O0.5 Singles (+133) • 56%","Cal Raleigh U1.5 TB (-180) • 66%"],["Anderson O5.5 K • 69%","Raleigh U1.5 TB • 66%"],["Anderson O5.5 K • 69%","Butler O0.5 Singles • 56%"],["Anderson O5.5 K • 69%","Raleigh U1.5 TB • 66%","Butler O0.5 Singles • 56%"],["Butler O0.5 RBI (+277) • 34%"],"Anderson strikeouts are the strongest probability-to-price channel in this matchup."),
        q("10:10 ET","STL","LAD","LAD ~-286 / STL +250 • O/U 7.5","Dodgers ML","73%",[WATCH],[WATCH],[WATCH],[WATCH],[WATCH],"Strong team-side read, but no player prop is promoted without a current verified line.")
      ]
    },
    NCAA_Football:{
      icon:"🏈",meta:"NCAA FOOTBALL • SEPTEMBER 3, 2026 • WEEK 1",kicker:"NCAA FOOTBALL DAILY QUICKIE",title:"NCAA FOOTBALL",
      description:"Week 1 is active. The approved QC layout is used for every September 3 game. Team sides are published where the matchup read is strong; player-prop cells remain WATCH until exact current markets are independently verified.",
      chips:[["11 GAMES TODAY","green"],["TEAM MARKETS LIVE","purple"],["PROP GATE ACTIVE","gold"]],
      hotTop:[["PLAYER PROP BOARD","WATCH","—","No 20-deep independently verified NCAA player-prop board has cleared the L&J gate yet; do not manufacture legs."]],
      winners:[
        ["Arkansas-Pine Bluff @ Missouri","Missouri","88%","Talent/depth gap"],["Eastern Illinois @ Minnesota","Minnesota","87%","Depth + home edge"],["Bethune-Cookman @ UCF","UCF","86%","Talent gap"],["UAB @ Illinois","Illinois","84%","Strong home favorite profile"],["Idaho @ Utah","Utah","82%","Home/talent edge"],["UMass @ Rutgers","Rutgers","79%","Rutgers around -29.5"],["Akron @ Wake Forest","Wake Forest","76%","Wake around -24.5"],["UAlbany @ Buffalo","Buffalo","69%","Home edge"],["Merrimack @ Delaware","Delaware","63%","Moderate lean"],["West Georgia @ Kennesaw State","Kennesaw State","61%","Moderate lean"],["Colorado @ Georgia Tech","Georgia Tech","59%","GT around -6.5"]
      ],twenty:empty20,twentyNote:"20 Piece section intentionally remains MARKET WATCH until 20 current NCAA player props can be verified. Team sides do not substitute for player props.",qcTitle:"PER-GAME QUICKIES — THURSDAY WEEK 1",
      qcs:[
        q("6:00 ET","UMASS","RUTGERS","Rutgers ~-29.5 • Total ~52.5","Rutgers","79%",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets(),"Do not force player props into the card."),
        q("7:00 ET","UALBANY","BUFFALO","Current team market live","Buffalo","69%",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets()),
        q("7:00 ET","AKRON","WAKE","Wake ~-24.5 • Total ~48.5–49.5","Wake Forest","76%",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets()),
        q("7:00 ET","MERRIMACK","DELAWARE","Current team market live","Delaware","63%",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets()),
        q("7:00 ET","B-C","UCF","Current team market live","UCF","86%",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets()),
        q("7:00 ET","W. GA","KENNESAW","Current team market live","Kennesaw State","61%",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets()),
        q("8:00 ET","E. ILL","MINN","Current team market live","Minnesota","87%",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets()),
        q("8:00 ET","COLO","GA TECH","Georgia Tech ~-6.5 • Total ~50.5","Georgia Tech","59%",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets(),"Competitive matchup; no false certainty."),
        q("8:00 ET","UAPB","MIZZOU","Heavy Missouri favorite","Missouri","88%",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets()),
        q("9:00 ET","UAB","ILLINOIS","Illinois heavy favorite","Illinois","84%",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets()),
        q("9:00 ET","IDAHO","UTAH","Utah heavy favorite","Utah","82%",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets())
      ]
    },
    NFL:{icon:"🏈",meta:"NFL • SEPTEMBER 3, 2026 • WEEK 1 PREVIEW",kicker:"NFL WEEK 1 INTELLIGENCE",title:"NFL PREDICTIONS",description:"No NFL game is scheduled today. Week 1 QCs stay preliminary until injuries, roles and exact current player markets clear the L&J verification gate. The layout is already in place and will not change when props populate.",chips:[["WEEK 1","gold"],["FINAL PROP GATE PENDING","purple"]],hotTop:[["PLAYER PROP BOARD","WATCH","—","Week 1 exact player markets are not yet sufficiently stable for a 20 Piece publication."]],winners:[["Sep 9 • Patriots @ Seahawks","Seattle early lean","64%","Final update pending"],["Sep 10 • 49ers vs Rams • Melbourne","Rams early lean","58%","Travel/neutral-site variance"],["Sep 13 • Cowboys @ Giants","WATCH","—","Final market pending"],["Sep 14 • Broncos @ Chiefs","WATCH","—","Final market pending"]],twenty:empty20,twentyNote:"20 Piece is present but not populated with stale preseason props. It will fill from verified Week 1 player markets only.",qcTitle:"UPCOMING WEEK 1 QUICKIES",qcs:[q("SEP 9 • 8:20 ET","NE","SEA","Opening week market • recheck before action","Seattle early lean","64%",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets(),"Final QC refresh after active-roster/injury confirmation."),q("SEP 10 • 8:35 ET","SF","LAR","Melbourne neutral/international setting","Rams early lean","58%",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets()),q("SEP 13","DAL","NYG","PRELIMINARY MARKET","WATCH","—",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets()),q("SEP 14","DEN","KC","PRELIMINARY MARKET","WATCH","—",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets())]},
    NBA:{icon:"🏀",meta:"NBA • SEPTEMBER 3, 2026 • OFFSEASON",kicker:"NBA DAILY STATUS",title:"NBA PREDICTIONS",description:"The NBA regular season has not started. Training camps open September 29, preseason begins October 3, and the regular season opens October 20. No stale props are carried forward.",chips:[["PRESEASON OCT 3","cyan"],["REGULAR SEASON OCT 20","gold"]],hotTop:[["PLAYER PROP BOARD","WATCH","—","No executable NBA player markets today."]],winners:[["Opening Night • Celtics vs Pistons","WATCH","—","Market pending"],["Opening Night • 76ers vs Knicks","WATCH","—","Market pending"],["Opening Night • Thunder vs Spurs","WATCH","—","Market pending"]],twenty:empty20,twentyNote:"20 Piece will populate only when opening-night player props are current and verified.",qcTitle:"OPENING NIGHT QUICKIE WATCH",qcs:[q("OCT 20","BOS","DET","MARKET WATCH","WATCH","—",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets()),q("OCT 20","PHI","NYK","MARKET WATCH","WATCH","—",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets()),q("OCT 20","OKC","SAS","MARKET WATCH","WATCH","—",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets())]},
    WNBA:{icon:"🏀",meta:"WNBA • SEPTEMBER 3, 2026 • WORLD CUP BREAK",kicker:"WNBA DAILY STATUS",title:"WNBA PREDICTIONS",description:"No WNBA games are scheduled today during the FIBA Women’s World Cup break. Play resumes September 17. No stale props remain active.",chips:[["RESUMES SEP 17","gold"],["NEXT-GAME ONLY","purple"]],hotTop:[["PLAYER PROP BOARD","WATCH","—","Post-World-Cup availability must be confirmed before player markets go live."]],winners:[["Sep 17 • Las Vegas @ Seattle","PRELIMINARY WATCH","—","Availability/market pending"]],twenty:empty20,twentyNote:"20 Piece is held blank until September 17 current player markets and post-World-Cup availability are verified.",qcTitle:"NEXT WNBA ACTION",qcs:[q("SEP 17","LVA","SEA","MARKET WATCH","WATCH","—",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets())]},
    NHL:{icon:"🏒",meta:"NHL • SEPTEMBER 3, 2026 • OFFSEASON",kicker:"NHL DAILY STATUS",title:"NHL PREDICTIONS",description:"The 2026-27 regular season begins September 29. Opening-night QCs are staged now; sides and player props remain WATCH until current markets and lineups are verified.",chips:[["SEASON START SEP 29","gold"],["OPENING NIGHT WATCH","purple"]],hotTop:[["PLAYER PROP BOARD","WATCH","—","No executable opening-night NHL player markets yet."]],winners:[["Florida @ Carolina","WATCH","—","Opening line pending"],["Montreal @ Toronto","WATCH","—","Opening line pending"],["Rangers @ Bruins","WATCH","—","Opening line pending"],["Blackhawks @ Golden Knights","WATCH","—","Opening line pending"]],twenty:empty20,twentyNote:"20 Piece will populate from current opening-night skater/goalie markets only.",qcTitle:"OPENING NIGHT QUICKIE WATCH",qcs:[q("SEP 29 • 5:00 ET","FLA","CAR","MARKET WATCH","WATCH","—",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets()),q("SEP 29 • 7:00 ET","MTL","TOR","MARKET WATCH","WATCH","—",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets()),q("SEP 29 • 8:00 ET","NYR","BOS","MARKET WATCH","WATCH","—",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets()),q("SEP 29 • 10:30 ET","CHI","VGK","MARKET WATCH","WATCH","—",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets())]},
    FIBA_Men:{icon:"🌍🏀",meta:"FIBA MEN • SEPTEMBER 3, 2026 • CALENDAR WATCH",kicker:"FIBA MEN DAILY STATUS",title:"FIBA MEN",description:"No senior men’s national-team game is scheduled today on the monitored calendar. Next announced events remain WATCH until matchup and market data become executable.",chips:[["NEXT EVENT WINDOW SEP 9+","gold"]],hotTop:[["PLAYER PROP BOARD","WATCH","—","No verified FIBA Men player market today."]],winners:[["Youth BCL Americas • Sep 9–12","WATCH","—","Matchups/markets pending"],["BCL Qualification • Sep 14–20","WATCH","—","Markets pending"],["FIBA Intercontinental Cup • Sep 22–27","WATCH","—","Opening slate pending"]],twenty:empty20,twentyNote:"20 Piece remains visible and blank rather than carrying stale or speculative player props.",qcTitle:"UPCOMING EVENT QUICKIE WATCH",qcs:[q("SEP 9–12","YOUTH BCL","AMERICAS","MATCHUP WATCH","WATCH","—",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets()),q("SEP 14–20","BCL","QUALIFICATION","MATCHUP WATCH","WATCH","—",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets()),q("SEP 22–27","FIBA","INTERCONTINENTAL","MATCHUP WATCH","WATCH","—",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets())]},
    FIBA_Women:{icon:"🌍🏀",meta:"FIBA WOMEN • SEPTEMBER 3, 2026 • WORLD CUP OPENS SEP 4",kicker:"FIBA WOMEN DAILY QUICKIE",title:"FIBA WOMEN",description:"Per the next-game-only rule, this page covers the September 4 opening slate only. September 5 games are not promoted. Exact player props stay WATCH until verified.",chips:[["WORLD CUP SEP 4–13","gold"],["NEXT DAY ONLY","purple"]],hotTop:[["PLAYER PROP BOARD","WATCH","—","Opening-day player markets have not cleared verification; do not fabricate props."]],winners:[["Japan vs Mali","Japan","71%","Opening slate"],["Australia vs Puerto Rico","Australia","86%","Strong lean"],["USA vs China","USA","91%","Strongest team-side lean"],["Korea vs Nigeria","Nigeria","62%","Moderate lean"],["Belgium vs Türkiye","Belgium","78%","Strong lean"],["Spain vs Germany","Spain","64%","Host factor lowers confidence"],["Czechia vs Italy","Italy","58%","Price-sensitive lean"],["Hungary vs France","France","76%","Strong lean"]],twenty:empty20,twentyNote:"20 Piece will populate when current FIBA player markets are verified. The section stays present now so the page structure never changes.",qcTitle:"SEPTEMBER 4 OPENING-SLATE QCs",qcs:[q("SEP 4 • 09:30 BERLIN","JPN","MLI","ODDS WATCH","Japan","71%",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets()),q("SEP 4 • 09:30","AUS","PUR","ODDS WATCH","Australia","86%",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets()),q("SEP 4 • 12:15","USA","CHN","ODDS WATCH","USA","91%",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets()),q("SEP 4 • 12:30","KOR","NGR","ODDS WATCH","Nigeria","62%",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets()),q("SEP 4 • 15:30","BEL","TUR","ODDS WATCH","Belgium","78%",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets()),q("SEP 4 • 15:45","ESP","GER","ODDS WATCH","Spain","64%",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets()),q("SEP 4 • 18:15","CZE","ITA","ODDS WATCH","Italy","58%",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets()),q("SEP 4 • 19:00","HUN","FRA","ODDS WATCH","France","76%",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets())]},
    NCAA_Basketball:{icon:"🏀",meta:"NCAA BASKETBALL • SEPTEMBER 3, 2026 • OFFSEASON",kicker:"NCAA BASKETBALL DAILY STATUS",title:"NCAA BASKETBALL",description:"The 2026-27 Division I season has not started. The first permissible contest date is November 2, 2026. No prior-season lines or props are retained.",chips:[["SEASON START NOV 2","gold"]],hotTop:[["PLAYER PROP BOARD","WATCH","—","No executable NCAA basketball player markets today."]],winners:[["2026-27 Opening Slate","WATCH","—","Schedules/markets pending"]],twenty:empty20,twentyNote:"20 Piece will populate from current opening-slate player markets only.",qcTitle:"PRESEASON QUICKIE WATCH",qcs:[q("NOV 2+","NCAA","BASKETBALL","SCHEDULE / MARKET WATCH","WATCH","—",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets())]},
    UFC:{icon:"🥊",meta:"UFC • UPDATED SEPTEMBER 3, 2026",kicker:"UFC DAILY INTELLIGENCE",title:"UFC PREDICTIONS",description:"Every announced UFC event receives the same locked QC structure. Winner/method/round markets populate as they are verified; unavailable markets remain WATCH.",chips:[["EVENT QCs LIVE","purple"],["METHOD / ROUND GATE","gold"]],hotTop:[["Salahdine Parnasse","Moneyline • approx. -550","82%","High win probability; price is expensive."],["Jose Miguel Delgado","Moneyline • approx. -350","76%","Strong early side; secondary props pending."],["Joshua Van","Moneyline slight lean • near -115","54%","Near-pick'em; do not overstate edge."]],winners:[["Sep 5 • Hooker vs Parnasse","Parnasse","82%","Approx. -550"],["Sep 12 • Silva vs Delgado","Delgado","76%","Approx. -350"],["Sep 19 • Van vs Pantoja 2","Joshua Van slight lean","54%","Near pick'em"],["Sep 26 • Rosas Jr. vs Barcelos","WATCH","—","Market incomplete"]],twenty:[["UFC","Salahdine Parnasse","To win","~ -550","82%","★★★★☆","🔥"],["UFC","Jose Miguel Delgado","To win","~ -350","76%","★★★★☆","🔥"],["UFC","Joshua Van","To win","~ -115","54%","★★★☆☆","🔥🔥"]],twentyNote:"Only three current UFC participant markets are promoted. The board does not fabricate seventeen filler selections to force a 20-count.",qcTitle:"UPCOMING EVENT QUICKIES",qcs:[q("SEP 5 • UFC PARIS","HOOKER","PARNASSE","Parnasse approx. -550 / Hooker +400","Parnasse","82%",["Parnasse ML • 82%","Method/round props • WATCH"],["Parnasse ML • 82%"],watchTickets(),["Parnasse ML • 82%"],watchTickets(),"Price sensitivity: very high. Win probability is strong; multiplier value is limited."),q("SEP 12 • NOCHE UFC","SILVA","DELGADO","Delgado approx. -350 / Silva +275","Delgado","76%",["Delgado ML • 76%","Method prop • WATCH"],["Delgado ML • 76%"],watchTickets(),["Delgado ML • 76%"],watchTickets()),q("SEP 19 • UFC 331","VAN","PANTOJA","Near Van -115 / Pantoja -105","Van slight lean","54%",["Main event ML • low edge","Method props • WATCH"],watchTickets(),watchTickets(),watchTickets(),watchTickets(),"Near-pick'em: do not force an SNS leg."),q("SEP 26","ROSAS JR.","BARCELOS","MARKET WATCH","WATCH","—",w(WATCH),watchTickets(),watchTickets(),watchTickets(),watchTickets())]},
    Boxing:{icon:"🥊",meta:"BOXING • UPDATED SEPTEMBER 3, 2026",kicker:"BOXING DAILY INTELLIGENCE",title:"BOXING PREDICTIONS",description:"Current fight QCs use the same locked horizontal format. Winner, method and round markets fill only after verification; missing markets stay WATCH.",chips:[["CURRENT FIGHTS","green"],["VALUE VS FLOOR","purple"]],hotTop:[["Lenar Perez","Moneyline • roughly -1200 to -1600","88%","Very high win probability, poor multiplier value."],["Andy Ruiz Jr.","KO/TKO/DQ • around +125","62%","Higher-value ceiling expression than the ML."],["Katie Taylor","Decision / Technical Decision • market dependent","72%","Better multiplier than prohibitive ML while matching recent profile."]],winners:[["Sep 3 • Perez vs Mchunu","Lenar Perez","88%","ML extremely expensive"],["Sep 4 • Ruiz vs Knyba","Andy Ruiz Jr.","69%","Approx. -250"],["Sep 5 • Taylor vs Pili","Katie Taylor","93%","ML roughly -1200 to -3000"]],twenty:[["BOX","Katie Taylor","To win","very heavy favorite","93%","★★★★★","🔥"],["BOX","Lenar Perez","To win","~ -1200 to -1600","88%","★★★★☆","🔥"],["BOX","Katie Taylor","Decision / Tech Decision","market dependent","72%","★★★★☆","🔥🔥"],["BOX","Andy Ruiz Jr.","To win","~ -250","69%","★★★★☆","🔥"],["BOX","Andy Ruiz Jr.","KO/TKO/DQ","~ +125","62%","★★★★☆","🔥🔥"]],twentyNote:"Five verified/usable participant markets are shown. The section remains 20 Piece by design, but L&J will not invent fifteen additional markets to fill space.",qcTitle:"EXECUTABLE EVENT QUICKIES",qcs:[q("SEP 3 • MONTREAL","PEREZ","MCHUNU","Perez roughly -1200 to -1600","Lenar Perez","88%",["Perez ML • 88%","Method/round • WATCH"],["Perez ML • 88%"],watchTickets(),["Perez ML anchor only • 88%"],watchTickets(),"High probability does not equal good value; do not overpay blindly."),q("SEP 4 • NEWARK","RUIZ","KNYBA","Ruiz approx. -250 / Knyba +200","Andy Ruiz Jr.","69%",["Ruiz ML • 69%","Ruiz KO/TKO/DQ (+125) • 62%"],["Ruiz ML • 69%"],["Ruiz ML • 69%","Ruiz KO/TKO/DQ • 62%"],["Ruiz KO/TKO/DQ (+125) • 62%"],watchTickets(),"Recheck weigh-in and final method price before upgrading the KO leg."),q("SEP 5 • CROKE PARK","TAYLOR","PILI","Taylor prohibitive favorite","Katie Taylor","93%",["Taylor ML • 93%","Taylor by Decision • 72%","Taylor KO/TKO/DQ • lower-confidence ceiling"],["Taylor ML • 93%"],["Taylor ML • 93%","Taylor Decision • 72%"],["Taylor by Decision • 72%"],["Taylor KO/TKO/DQ • ceiling only"],"Decision is the preferred value channel; KO is the higher-variance alternate.")]}
  };

  const home = {
    meta:"THURSDAY • SEPTEMBER 3, 2026 • DAILY ISSUE",kicker:"INDEPENDENT DAILY ISSUE",title:"LEGZ & JINX DAILY PREDICTIONS",
    description:"All-sports publication hub. Every sport page uses the same approved QC design. Daily refreshes update current odds, props, predictions and status only — not the presentation architecture.",
    chips:[["TODAY'S QCs","green"],["NEXT EVENT QCs","purple"],["LAYOUT LOCKED","gold"]],
    hotTop:[
      ["MLB • Kade Anderson","Over 5.5 K • -105","69%","Best current strikeout channel."],
      ["MLB • Jake Bauers","Over 0.5 Hits • -156","68%","Contact-floor expression."],
      ["MLB • Brandon Young","Under 17.5 Outs • -125","65%","Leash + matchup under."],
      ["MLB • Yordan Alvarez","Over 0.5 Walks • -117","64%","Elite walk channel."],
      ["BOX • Katie Taylor","Decision / Technical Decision","72%","Preferred multiplier-vs-floor fight expression."],
      ["BOX • Andy Ruiz Jr.","KO/TKO/DQ • ~+125","62%","Ceiling expression."],
      ["UFC • Salahdine Parnasse","To win • ~-550","82%","High probability, expensive price."]
    ],
    winners:[
      ["FIBA • USA vs China","USA","91%","Sep 4"],["BOX • Taylor vs Pili","Katie Taylor","93%","Sep 5"],["NCAA • UAPB @ Missouri","Missouri","88%","Tonight"],["BOX • Perez vs Mchunu","Lenar Perez","88%","Sep 3"],["NCAA • E. Illinois @ Minnesota","Minnesota","87%","Tonight"],["NCAA • Bethune-Cookman @ UCF","UCF","86%","Tonight"],["FIBA • Australia vs Puerto Rico","Australia","86%","Sep 4"],["UFC • Hooker vs Parnasse","Parnasse","82%","Sep 5"],["MLB • STL @ LAD","Dodgers","73%","Tonight"],["MLB • ATH @ SEA","Mariners","66%","Tonight"]
    ],
    twenty:mlb20,
    twentyNote:"GLOBAL 20 PIECE: today’s deepest verified participant-prop board is MLB, so the all-sports pool is MLB-heavy rather than artificially diversified. Other sports enter when comparable current player/participant markets are verified."
  };
  return {date:"September 3, 2026",updated:"Late-morning refresh • Sep 3, 2026",nav,home,sports};
})();