/* LEGZ & JINX DAILY DATA
   2026-09-05 09:00 PT DAY-OF REFRESH.
   DATA ONLY. QC/page presentation remains locked in ljapp.js + ljqc.css. */
window.LJ_DATA = (() => {
  const WATCH = "WATCH — no independently verified current player/participant market cleared the L&J gate";
  const NO_BET = "NO BET — current evidence does not support an executable selection";
  const CLOSED = "CLOSED / LIVE — event has started; no new pregame action and no chasing";
  const nav = [
    ["MLB","⚾","MLB.html"],["NFL","🏈","NFL.html"],["NBA","🏀","NBA.html"],["WNBA","🏀","WNBA.html"],["NHL","🏒","NHL.html"],
    ["FIBA MEN","🌍🏀","FIBA_Men.html"],["FIBA WOMEN","🌍🏀","FIBA_Women.html"],["NCAA FOOTBALL","🏈","NCAA_Football.html"],
    ["NCAA BASKETBALL","🏀","NCAA_Basketball.html"],["UFC","🥊","UFC.html"],["BOXING","🥊","Boxing.html"],["TENNIS","🎾","Tennis.html"]
  ];
  const q=(time,away,home,market,winner,conf,hot,sns1,sns2,normal,demon,foot="")=>({time,away,home,market,winner,conf,hot,sns1,sns2,normal,demon,foot});
  const w=x=>[x];
  const W=()=>[WATCH];
  const twentyRow=(sport,name,pred,price,conf,quality="★★★★☆",risk="🔥")=>[sport,name,pred,price,conf,quality,risk];

  const mlb20 = [
    twentyRow("MLB","Parker Messick","Over 6.5 strikeouts","+114","64%","★★★★☆","🔥🔥"),
    twentyRow("MLB","Yordan Alvarez","1+ home run","+240","31%","★★★★☆","🔥🔥🔥"),
    twentyRow("MLB","Corbin Carroll","1+ home run","+340","25%","★★★☆☆","🔥🔥🔥"),
    twentyRow("MLB","Junior Caminero","1+ home run","+285","28%","★★★☆☆","🔥🔥🔥"),
    twentyRow("MLB","Corey Seager","1+ home run","+300","27%","★★★☆☆","🔥🔥🔥")
  ];
  const cfb20 = [
    twentyRow("NCAA FOOTBALL","Mason McKenzie","Under 184.5 passing yards","-114","64%","★★★★☆","🔥"),
    twentyRow("NCAA FOOTBALL","Byrum Brown","Under 73.5 rushing yards","-114","60%","★★★☆☆","🔥🔥"),
    twentyRow("NCAA FOOTBALL","Sam Leavitt","Over 254.5 passing yards","-114","58%","★★★☆☆","🔥🔥")
  ];
  const tennis20 = [
    twentyRow("TENNIS","Coco Gauff","Match winner","-2500 to -3300","93%","★★★☆☆","🔥"),
    twentyRow("TENNIS","Taylor Fritz","Match winner","-680 to -700","86%","★★★★☆","🔥"),
    twentyRow("TENNIS","Alexander Zverev","Match winner","-690 to -770","86%","★★★★☆","🔥"),
    twentyRow("TENNIS","Amanda Anisimova","Match winner","-500","83%","★★★★☆","🔥"),
    twentyRow("TENNIS","Iga Swiatek","Match winner","-600","85%","★★★★☆","🔥"),
    twentyRow("TENNIS","Elena Rybakina","Match winner","-1200","90%","★★★☆☆","🔥"),
    twentyRow("TENNIS","Flavio Cobolli","Match winner","-116 to -125","56%","★★★★☆","🔥🔥")
  ];
  const ufc20 = [
    twentyRow("UFC","Salahdine Parnasse","Fight winner","-550","84%","★★★★☆","🔥"),
    twentyRow("UFC","Nathaniel Wood","Fight winner","-315","76%","★★★★☆","🔥"),
    twentyRow("UFC","Mario Pinto","Fight winner","-305","75%","★★★★☆","🔥"),
    twentyRow("UFC","Oumar Sy","Fight winner","-230","69%","★★★★☆","🔥"),
    twentyRow("UFC","Felipe Lima","Fight winner","-185","65%","★★★☆☆","🔥🔥"),
    twentyRow("UFC","Farès Ziam","Fight winner","-150","59%","★★★☆☆","🔥🔥")
  ];
  const boxing20 = [
    twentyRow("BOXING","Katie Taylor","Fight winner","1.04 / about -2500","94%","★★★☆☆","🔥"),
    twentyRow("BOXING","Katie Taylor","Win by decision","1.44 / about -227","76%","★★★★☆","🔥🔥")
  ];

  const mlbGames = [
    q("4:10 ET • 1:10 PT","SF","NYM","NYM -180 / SF +152 • total market recheck","Mets ML lean","55%",W(),W(),W(),W(),W(),"Official probable-pitcher board and sportsbook feeds showed some disagreement in the morning sweep; do not manufacture a player leg."),
    q("4:10 ET • 1:10 PT","CHC","MIA","CHC -138 / MIA +118","Cubs ML lean","54%",W(),W(),W(),W(),W(),"Official probable-pitcher information supersedes older market blurbs. Player board stays WATCH until the matchup is reconciled."),
    q("6:05 ET • 3:05 PT","ATL","PHI","PHI -158 / ATL +134","Phillies ML","61%",W(),W(),W(),W(),W(),"Zack Wheeler / Martin Perez matchup supports Philadelphia; hitter props remain lineup-gated."),
    q("6:10 ET • 3:10 PT","DET","CLE","CLE -154 / DET +130","Guardians ML","59%",["Parker Messick O6.5 K (+114) • 64%"],["Messick O6.5 K • 64%"],W(),["Messick O6.5 K (+114) • 64%"],W(),"Messick is the one current prop with a clean multi-source case. Remove if starter/status changes."),
    q("6:40 ET • 3:40 PT","MIL","CIN","MIL -162 / CIN +136","Brewers ML","69%",W(),W(),W(),W(),W(),"numberFire win projection strongly supports Milwaukee; no current player line cleared verification."),
    q("6:40 ET • 3:40 PT","LAA","PIT","PIT -178 / LAA +150","Pirates ML","68%",W(),W(),W(),W(),W(),"Strong team-side projection; prop cells stay WATCH rather than borrowing a stale line."),
    q("7:05 ET • 4:05 PT","BOS","BAL","BOS -138 / BAL +118","Red Sox ML lean","56%",W(),W(),W(),W(),W(),"Only a modest team edge. Avoid forcing hitter props before confirmed batting orders."),
    q("7:05 ET • 4:05 PT","TB","TEX","TB -108 / TEX -108","PASS / Rangers hairline model lean","51%",["Junior Caminero HR (+285) • 28%","Corey Seager HR (+300) • 27%"],W(),W(),W(),["Caminero HR +285 • 28%","Seager HR +300 • 27%"],"Moneyline is essentially a coin flip. HRs belong only in Demon/ceiling construction."),
    q("7:10 ET • 4:10 PT","TOR","KC","KC -110 / TOR -106","Royals ML lean","61%",W(),W(),W(),W(),W(),"Morning pitcher/prop feeds conflict; side can stand, player board cannot until official starter + market align."),
    q("7:10 ET • 4:10 PT","MIN","CWS","CWS -124 / MIN +106","Twins value lean","55%",W(),W(),W(),W(),W(),"numberFire prefers Minnesota despite market favorite Chicago. Treat as value lean, not SNS."),
    q("7:15 ET • 4:15 PT","NYY","SD","SD -116 / NYY -102","PASS / Yankees model hairline lean","52%",W(),W(),W(),W(),W(),"Near coin flip and morning pitcher-market conflict; no player leg promoted."),
    q("7:15 ET • 4:15 PT","ARI","HOU","ARI -108 / HOU -108","PASS / Astros hairline lean","52%",["Yordan Alvarez HR (+240) • 31%","Corbin Carroll HR (+340) • 25%"],W(),W(),W(),["Alvarez HR +240 • 31%","Carroll HR +340 • 25%"],"Side is a coin flip. Home-run legs are ceiling-only and never SNS."),
    q("8:10 ET • 5:10 PT","STL","COL","STL -120 / COL +102","Cardinals ML","60%",W(),W(),W(),W(),W(),"St. Louis has the cleaner model edge; no verified player market cleared morning QC."),
    q("9:10 ET • 6:10 PT","WSH","LAD","LAD -230 / WSH +190","Dodgers ML","63%",W(),W(),W(),W(),W(),"Strongest late team favorite; price is expensive. Do not treat price as value."),
    q("9:40 ET • 6:40 PT","ATH","SEA","SEA -250 / ATH +205","Mariners ML","61%",W(),W(),W(),W(),W(),"Raw win edge is solid but -250 is poor multiplier efficiency; prop board stays WATCH.")
  ];

  const cfbRaw = [
    ["12:00 ET • 9:00 PT","ECU","ALABAMA","ALA -28.5 • O/U 54.5"],["12:00 ET • 9:00 PT","OREGON ST","HOUSTON","HOU -20.5 • O/U 50.5"],["12:00 ET • 9:00 PT","COASTAL CAR","WEST VIRGINIA","WVU -21.5 • O/U 58.5"],["12:00 ET • 9:00 PT","NEW HAMPSHIRE","SYRACUSE","SYR -32.5 • O/U 55.5"],["12:00 ET • 9:00 PT","NORTH TEXAS","INDIANA","IND -40.5 • O/U 55.5"],["12:00 ET • 9:00 PT","OHIO","NEBRASKA","NEB -23.5 • O/U 47.5"],["12:00 ET • 9:00 PT","LAFAYETTE","UCONN","UCONN -18.5 • O/U 58.5"],["12:00 ET • 9:00 PT","BRYANT","ARMY","ARMY -36.5 • O/U 51.5"],["12:00 ET • 9:00 PT","TARLETON ST","BOWLING GREEN","BGSU -1.5 • O/U 47.5"],["12:00 ET • 9:00 PT","LIBERTY","JAMES MADISON","JMU -6 • O/U 51.5"],
    ["12:30 ET • 9:30 PT","MIAMI OH","PITTSBURGH","PITT -16.5 • O/U 50.5"],["12:30 ET • 9:30 PT","BALL ST","OHIO ST","OSU -50.5 • O/U 56.5"],["12:45 ET • 9:45 PT","KENT ST","SOUTH CAROLINA","SC -36.5 • O/U 53.5"],
    ["1:00 ET • 10:00 PT","YOUNGSTOWN ST","KENTUCKY","UK -23.5 • O/U 62.5"],["1:00 ET • 10:00 PT","SE MISSOURI ST","IOWA ST","ISU -29.5 • O/U 54.5"],["1:00 ET • 10:00 PT","DUQUESNE","AIR FORCE","AF -28.5 • O/U 58.5"],["2:00 ET • 11:00 PT","RHODE ISLAND","TEMPLE","TEM -10 • O/U 51.5"],["3:00 ET • 12:00 PT","TENNESSEE ST","GEORGIA","UGA -44.5 • O/U 56.5"],
    ["3:30 ET • 12:30 PT","BAYLOR","AUBURN","AUB -7 • O/U 59.5"],["3:30 ET • 12:30 PT","FURMAN","TENNESSEE","TENN -46.5 • O/U 66.5"],["3:30 ET • 12:30 PT","TEXAS ST","TEXAS","TEX -30.5 • O/U 60.5"],["3:30 ET • 12:30 PT","BOSTON COLLEGE","CINCINNATI","CIN -7.5 • O/U 54.5"],["3:30 ET • 12:30 PT","TULANE","DUKE","DUKE -9.5 • O/U 52.5"],["3:30 ET • 12:30 PT","BOISE ST","OREGON","ORE -24.5 • O/U 52.5"],["3:30 ET • 12:30 PT","MARSHALL","PENN ST","PSU -24.5 • O/U 54.5"],["3:30 ET • 12:30 PT","CITADEL","CHARLOTTE","CLT -10.5 • O/U 46.5"],["3:30 ET • 12:30 PT","TOWSON","NAVY","NAVY -30.5 • O/U 53.5"],["3:30 ET • 12:30 PT","UTRGV","UTSA","UTSA -28.5 • O/U 59.5"],["3:30 ET • 12:30 PT","FORDHAM","N DAKOTA ST","NDSU -39.5 • O/U 57.5"],["3:30 ET • 12:30 PT","MAINE","APP ST","APP -17.5 • O/U 53.5"],
    ["3:45 ET • 12:45 PT","OKLAHOMA ST","TULSA","OKST -14 • O/U 61.5"],["4:15 ET • 1:15 PT","NORTH ALABAMA","ARKANSAS","ARK -40.5 • O/U 63.5"],["4:15 ET • 1:15 PT","N ILLINOIS","IOWA","IOWA -30.5 • O/U 45.5"],["5:00 ET • 2:00 PT","ALCORN ST","SOUTHERN MISS","USM -21 • O/U 50.5"],["6:00 ET • 3:00 PT","WYOMING","COLORADO ST","CSU -3.5 • O/U 47.5"],["6:00 ET • 3:00 PT","NORFOLK ST","OLD DOMINION","ODU -41.5 • O/U 55.5"],
    ["7:00 ET • 4:00 PT","MISSOURI ST","TEXAS A&M","TAMU -39.5 • O/U 52.5"],["7:00 ET • 4:00 PT","AUSTIN PEAY","VANDERBILT","VAN -30.5 • O/U 61.5"],["7:00 ET • 4:00 PT","ABILENE CHRISTIAN","TEXAS TECH","TTU -42.5 • O/U 59.5"],["7:00 ET • 4:00 PT","NICHOLLS","KANSAS ST","KSU -40.5 • O/U 55.5"],["7:00 ET • 4:00 PT","IDAHO ST","UTAH ST","USU -11.5 • O/U 64.5"],["7:00 ET • 4:00 PT","ARKANSAS ST","MEMPHIS","MEM -10 • O/U 55.5"],["7:00 ET • 4:00 PT","HOUSTON CHRISTIAN","RICE","RICE -23.5 • O/U 47.5"],["7:00 ET • 4:00 PT","FIU","SOUTH FLORIDA","USF -12.5 • O/U 54.5"],["7:00 ET • 4:00 PT","MURRAY ST","MIDDLE TENN","MTSU -20.5 • O/U 59.5"],["7:00 ET • 4:00 PT","E KENTUCKY","JACKSONVILLE ST","JXST -19.5 • O/U 52.5"],["7:00 ET • 4:00 PT","CHARLESTON SOUTHERN","GEORGIA SOUTHERN","GASO -25.5 • O/U 51.5"],["7:00 ET • 4:00 PT","SE LOUISIANA","SOUTH ALABAMA","USA -12.5 • O/U 52.5"],["7:00 ET • 4:00 PT","SAM HOUSTON","TROY","TROY -15.5 • O/U 51.5"],
    ["7:30 ET • 4:30 PT","CLEMSON","LSU","LSU -9.5 • O/U 50.5"],["7:30 ET • 4:30 PT","ULM","MISSISSIPPI ST","MSST -28.5 • O/U 55.5"],["7:30 ET • 4:30 PT","VMI","VIRGINIA TECH","VT -50.5 • O/U 57.5"],["7:30 ET • 4:30 PT","W MICHIGAN","MICHIGAN","MICH -26.5 • O/U 47.5"],["7:30 ET • 4:30 PT","NW STATE","LOUISIANA TECH","LT -41.5 • O/U 52.5"],["7:45 ET • 4:45 PT","FAU","FLORIDA","FLA -26.5 • O/U 58.5"],
    ["8:00 ET • 5:00 PT","UTAH TECH","BYU","BYU -47.5 • O/U 54.5"],["8:00 ET • 5:00 PT","HAMPTON","MARYLAND","MD -45.5 • O/U 56.5"],["8:00 ET • 5:00 PT","S DAKOTA ST","NORTHWESTERN","NU -11.5 • O/U 46.5"],["8:00 ET • 5:00 PT","LAMAR","LOUISIANA","ULL -18.5 • O/U 48.5"],["9:00 ET • 6:00 PT","MORGAN ST","ARIZONA ST","ASU -41.5 • O/U 52.5"],["9:00 ET • 6:00 PT","MERCYHURST","NEW MEXICO ST","NMSU -24.5 • O/U 50.5"],["9:30 ET • 6:30 PT","N ARIZONA","ARIZONA","ARIZ -31.5 • O/U 56.5"],["9:30 ET • 6:30 PT","PORTLAND ST","SAN DIEGO ST","SDSU -38.5 • O/U 57.5"],
    ["10:00 ET • 7:00 PT","UNLV","HAWAII","UNLV -2.5 • O/U 58.5"],["10:00 ET • 7:00 PT","CENTRAL MICHIGAN","NEW MEXICO","UNM -12.5 • O/U 48.5"],["10:00 ET • 7:00 PT","MISS VALLEY ST","SACRAMENTO ST","SAC -35.5 • O/U 57.5"],["10:30 ET • 7:30 PT","UCLA","CAL","UCLA -1.5 • O/U 54.5"],["10:30 ET • 7:30 PT","WKU","NEVADA","WKU -2.5 • O/U 52.5"]
  ];
  const cfbConf = market => { const m=market.match(/-([0-9]+(?:\.5)?)/); const s=m?parseFloat(m[1]):0; return s>=40?"90%":s>=30?"86%":s>=20?"80%":s>=14?"72%":s>=10?"68%":s>=7?"64%":s>=3?"58%":"53%"; };
  const cfbFav = market => market.split(" -")[0].replace(/\s*\(.*/,"");
  const cfbQ = cfbRaw.map(([time,away,home,market])=>{
    let fav=cfbFav(market), conf=cfbConf(market), hot=W(), sns1=W(), sns2=W(), normal=W(), demon=W(), foot="Dedicated multi-source player-prop sweep completed; no current executable player line was inserted unless verified below.";
    if(away==="BAYLOR"&&home==="AUBURN"){hot=["Byrum Brown U73.5 rush yds (-114) • 60% — line moved from earlier article threshold; price/threshold sensitive"]; normal=["Brown U73.5 rush yds • 60%"]}
    if(away==="BOSTON COLLEGE"&&home==="CINCINNATI"){hot=["Mason McKenzie U184.5 pass yds (-114) • 64%"] ; sns1=["McKenzie U184.5 pass yds • 64%"]}
    if(away==="CLEMSON"&&home==="LSU"){hot=["Sam Leavitt O254.5 pass yds (-114) • 58%"] ; normal=["Leavitt O254.5 pass yds • 58%"]}
    if(away==="WYOMING"&&home==="COLORADO ST"){fav="Wyoming value lean";conf="54%";foot="Action Network surfaced Wyoming ML +135 value; underdog selection remains Normal/value, not SNS."}
    if(away==="CENTRAL MICHIGAN"&&home==="NEW MEXICO"){fav="Central Michigan value lean";conf="53%";foot="New Mexico QB Jack Layne is out for the season; Luke Moga steps in. Action Network identified CMU ML upset value."}
    if(away==="WKU"&&home==="NEVADA"){fav="Nevada value lean";conf="53%";foot="Action Network surfaced Nevada ML +120. Treat as thin value, not a high-confidence winner."}
    return q(time,away,home,market,fav,conf,hot,sns1,sns2,normal,demon,foot);
  });

  const tennisQ = [
    q("Arthur Ashe • 11:30 ET / 8:30 PT","TAYLOR FRITZ [9]","FRANCISCO CERUNDOLO [24]","Fritz -680 to -700 / Cerundolo +446 to +500","Fritz","86%",["Fritz ML • 86%"],["Fritz ML • 86%"],W(),W(),W(),"Very expensive favorite; confidence is high but price efficiency is poor. Do not call the ML a value play."),
    q("Arthur Ashe • NOT BEFORE 1:30 ET / 10:30 PT","CRISTINA BUCSA","COCO GAUFF [4]","Gauff -2500 to -3300 / Bucsa +1200+","Gauff","93%",["Gauff ML • 93%"],["Gauff ML • 93%"],W(),W(),W(),"ML is accuracy-first only; value requires a separately verified spread/set market."),
    q("Arthur Ashe • NIGHT SESSION 7:00 ET / 4:00 PT","IVA JOVIC [14]","ALEXANDRA EALA [17]","Jovic about -118 / Eala +110","Jovic lean","53%",W(),W(),W(),W(),W(),"Near coin flip. No reason to force a side."),
    q("Arthur Ashe • FOLLOWS Jovic/Eala","ALEXANDER ZVEREV [1]","ALEJANDRO TABILO [25]","Zverev -690 to -770 / Tabilo +486 to +510 • total 36.5","Zverev","86%",["Zverev ML • 86%"],["Zverev ML • 86%"],W(),W(),W(),"Zverev just survived a five-set match; fatigue is the kill switch despite the large talent/market edge."),
    q("Louis Armstrong • 11:00 ET / 8:00 PT","ANASTASIA POTAPOVA [24]","AMANDA ANISIMOVA [10]","Anisimova about -500 / Potapova +470","Anisimova","83%",["Anisimova ML • 83%"],["Anisimova ML • 83%"],W(),W(),W(),"Strong favorite; monitor live status because this is the first Armstrong match and can begin before publication refresh propagates."),
    q("Louis Armstrong • FOLLOWS Potapova/Anisimova","ALEXANDER BLOCKX [28]","FLAVIO COBOLLI [5]","Cobolli -116 to -125 / Blockx +100","Cobolli lean","56%",["Cobolli ML -116 to -125 • 56%","Cobolli -1.5 games +110 snapshot • 54%"],W(),W(),["Cobolli ML • 56%"],W(),"Close match. Action Network preference is Cobolli experience/consistency; do not elevate to SNS."),
    q("US Open day session • official court order governs","IGA SWIATEK","MARIE BOUZKOVA","Swiatek about -600 / Bouzkova +461 to +500","Swiatek","85%",["Swiatek ML • 85%"],["Swiatek ML • 85%"],W(),W(),W(),"Exact court sequence should follow official order of play; price is too steep for value-focused Normal construction."),
    q("US Open day/evening order • official court assignment governs","YULIIA STARODUBTSEVA","ELENA RYBAKINA","Rybakina about -1200 / Starodubtseva +800","Rybakina","90%",["Rybakina ML • 90%"],["Rybakina ML • 90%"],W(),W(),W(),"High confidence, low price efficiency; no invented set line.")
  ];

  const ufcFights = [
    ["PRELIMS • 12:00 ET / 9:00 PT","Morgan Charriere","Felipe Lima","Charriere +155 / Lima -185","Felipe Lima","65%"],
    ["PRELIMS • 12:00 ET / 9:00 PT","Mario Pinto","Ryan Spann","Pinto -305 / Spann +245","Mario Pinto","75%"],
    ["PRELIMS • 12:00 ET / 9:00 PT","Oumar Sy","Modestas Bukauskas","Sy -230 / Bukauskas +190","Oumar Sy","69%"],
    ["PRELIMS • 12:00 ET / 9:00 PT","Nathaniel Wood","Pavel Andrusca","Wood -315 / Andrusca +250","Nathaniel Wood","76%"],
    ["PRELIMS • 12:00 ET / 9:00 PT","Michael Aljarouj","Fabia Sintes","Aljarouj -125 / Sintes +105","Aljarouj lean","55%"],
    ["PRELIMS • official bout order","Nora Cornolle","Klaudia Sygula","Winner market WATCH","WATCH","—"],
    ["PRELIMS • official bout order","Matthieu Duclos","Luis Felipe Dias","Winner market WATCH","WATCH","—"],
    ["PRELIMS • official bout order","Delphine Benouaich","Sofia Montenegro","Winner market WATCH","WATCH","—"],
    ["MAIN CARD • 3:00 ET / 12:00 PT","Losene Keita","Muhammad Naimov","Winner market WATCH","WATCH","—"],
    ["MAIN CARD • official bout order","Kurtis Campbell","Trevor Peek","Winner market WATCH","WATCH","—"],
    ["MAIN CARD • official bout order","Daniil Donchenko","Punahele Soriano","Winner market WATCH","WATCH","—"],
    ["MAIN CARD • official bout order","Michael Venom Page","Nursulton Ruziboev","Winner market WATCH","WATCH","—"],
    ["CO-MAIN • main card","Farès Ziam","Axel Sola","Ziam -150 / Sola +125","Farès Ziam","59%"],
    ["MAIN EVENT • main card","Dan Hooker","Salahdine Parnasse","Hooker +400 / Parnasse -550","Salahdine Parnasse","84%"]
  ].map(([time,away,home,market,winner,conf])=>q(time,away,home,market,winner,conf,winner==="WATCH"?W():[`${winner} ML • ${conf}`],winner==="WATCH"?W():[`${winner} ML • ${conf}`],W(),W(),W(),"Official UFC weigh-ins are complete. Method/round props remain WATCH unless separately verified; late replacement Pavel Andrusca remains a volatility flag."));

  const nflRaw = [
    ["WED SEP 9 • 8:20 ET / 5:20 PT","NE","SEA","SEA -3.5 consensus • total ~44.5 • SEA ML around -195","Seahawks","64%"],
    ["THU SEP 10 • 8:35 ET / 5:35 PT","SF","LAR","LAR -2.5 to -3.5 • total ~48.5","Rams","61%"],
    ["SUN SEP 13 • 1:00 ET / 10:00 PT","CHI","CAR","CHI -2.5","Bears lean","57%"],["SUN SEP 13 • 1:00 ET / 10:00 PT","TB","CIN","CIN -3.5 • total ~51","Bengals","60%"],["SUN SEP 13 • 1:00 ET / 10:00 PT","NO","DET","DET -7","Lions","68%"],["SUN SEP 13 • 1:00 ET / 10:00 PT","BUF","HOU","pick'em to BUF -1.5","PASS / Bills hairline lean","51%"],["SUN SEP 13 • 1:00 ET / 10:00 PT","BAL","IND","BAL -3.5","Ravens","62%"],["SUN SEP 13 • 1:00 ET / 10:00 PT","CLE","JAX","JAX -7 to -7.5","Jaguars","68%"],["SUN SEP 13 • 1:00 ET / 10:00 PT","ATL","PIT","PIT -2.5 to -3","Steelers lean","57%"],["SUN SEP 13 • 1:00 ET / 10:00 PT","NYJ","TEN","TEN -2.5 to -3","Titans lean","56%"],
    ["SUN SEP 13 • 4:25 ET / 1:25 PT","ARI","LAC","LAC -9.5 to -11.5","Chargers","75%"],["SUN SEP 13 • 4:25 ET / 1:25 PT","MIA","LV","LV -3","Raiders","59%"],["SUN SEP 13 • 4:25 ET / 1:25 PT","GB","MIN","GB -1.5","PASS / Packers hairline lean","53%"],["SUN SEP 13 • 4:25 ET / 1:25 PT","WAS","PHI","PHI -4.5 to -5.5","Eagles","65%"],["SUN SEP 13 • 8:20 ET / 5:20 PT","DAL","NYG","DAL -2.5","Cowboys lean","57%"],["MON SEP 14 • 8:15 ET / 5:15 PT","DEN","KC","KC -2.5","Chiefs lean","58%"]
  ];
  const nflQ = nflRaw.map(x=>q(x[0],x[1],x[2],x[3],x[4],x[5],W(),W(),W(),W(),W(),"Week 1 player markets remain early-cycle. No stale preseason prop is reused; Wednesday/Thursday/Saturday refreshes must translate verified live props into these locked cells."));

  const sports = {
    MLB:{icon:"⚾",meta:"MLB DAILY • SEPTEMBER 5, 2026 • 9:00 AM PT REFRESH",kicker:"MLB DAILY QUICKIE",title:"MLB PREDICTIONS",description:"Saturday’s 15-game MLB slate has been hard-corrected from the stale September 3 publication. Current team markets are refreshed; player cells remain WATCH wherever morning starter/market feeds conflict or a supportable prop is unavailable.",chips:[["15 GAMES TODAY","green"],["MORNING REFRESH","purple"],["LINEUP GATES ACTIVE","gold"]],hotTop:[["Parker Messick","Over 6.5 K • +114","64%","Best verified current strikeout expression in the morning sweep."],["Yordan Alvarez","1+ HR • +240","31%","Demon-only ceiling market; not an SNS leg."],["Junior Caminero","1+ HR • +285","28%","Ceiling-only; matchup side is a coin flip."]],winners:[["MIL @ CIN","Brewers ML","69%","MIL -162; numberFire 69.6%"],["LAA @ PIT","Pirates ML","68%","PIT -178; numberFire 69.0%"],["WSH @ LAD","Dodgers ML","63%","LAD -230"],["ATH @ SEA","Mariners ML","61%","SEA -250; expensive"],["ATL @ PHI","Phillies ML","61%","PHI -158"]],twenty:mlb20,twentyNote:"Only current independently verified player markets are shown. The 20 Piece is intentionally not padded to twenty with stale or invented legs.",qcTitle:"PER-GAME QUICKIES — SATURDAY, SEPTEMBER 5",qcs:mlbGames},

    NCAA_Football:{icon:"🏈",meta:"NCAA FOOTBALL • SEPTEMBER 5, 2026 • SATURDAY SLATE",kicker:"NCAA FOOTBALL QUICKIE",title:"NCAA FOOTBALL",description:"Saturday Week 1 slate refreshed from ESPN current schedule/markets plus Action/FanDuel player-prop sweeps. Every listed game carries ET and PT kickoff. Player cells stay WATCH unless a current exact threshold was verified.",chips:[["SATURDAY SLATE","green"],["KICKOFF TIMES VERIFIED","purple"],["PLAYER PROP SWEEP COMPLETE","gold"]],hotTop:[["Mason McKenzie","Under 184.5 pass yds • -114","64%","Cincinnati matchup; cleanest current CFB player-prop expression."],["Byrum Brown","Under 73.5 rush yds • -114","60%","Current widget threshold; earlier article showed a lower line, so line drift matters."],["Sam Leavitt","Over 254.5 pass yds • -114","58%","High-profile Clemson/LSU volume target; Normal, not SNS."]],winners:[["ECU @ Alabama","Alabama","84%","ALA -28.5"],["Boise St @ Oregon","Oregon","81%","ORE -24.5"],["Clemson @ LSU","LSU","66%","LSU -9.5"],["Baylor @ Auburn","Auburn","62%","AUB -7"],["UCLA @ Cal","PASS / UCLA hairline lean","53%","UCLA -1.5"]],twenty:cfb20,twentyNote:"Three exact player markets cleared this morning’s multi-source gate. The section remains deliberately short rather than converting team sides into player props.",qcTitle:"PER-GAME QUICKIES — SATURDAY WEEK 1",qcs:cfbQ},

    Tennis:{icon:"🎾",meta:"TENNIS • US OPEN • SEPTEMBER 5, 2026",kicker:"US OPEN DAILY QUICKIE",title:"TENNIS",description:"US Open third-round coverage uses the official order of play. Exact official FOLLOWS / NOT BEFORE / NIGHT SESSION designations are retained rather than inventing start times.",chips:[["US OPEN R3","green"],["OFFICIAL OOP","purple"],["CURRENT WIN MARKETS","gold"]],hotTop:[["Coco Gauff","Match winner • -2500 to -3300","93%","Highest raw hit confidence; price is inefficient."],["Elena Rybakina","Match winner • around -1200","90%","High-confidence favorite, low multiplier."],["Taylor Fritz","Match winner • -680 to -700","86%","Strong favorite vs Cerundolo."],["Alexander Zverev","Match winner • -690 to -770","86%","Talent edge offset by recent five-set fatigue."],["Amanda Anisimova","Match winner • around -500","83%","Strong favorite vs Potapova."],["Flavio Cobolli","Match winner • -116 to -125","56%","Best balanced value among highlighted matches."]],winners:[["Fritz vs Cerundolo","Fritz","86%","Arthur Ashe 11:30 ET"],["Bucsa vs Gauff","Gauff","93%","NOT BEFORE 1:30 ET"],["Jovic vs Eala","Jovic lean","53%","Night session; near coin flip"],["Zverev vs Tabilo","Zverev","86%","FOLLOWS Jovic/Eala"],["Potapova vs Anisimova","Anisimova","83%","Louis Armstrong 11:00 ET"],["Blockx vs Cobolli","Cobolli lean","56%","FOLLOWS prior Armstrong match"]],twenty:tennis20,twentyNote:"Match-winner confidence and betting value are not the same. Expensive favorites remain accuracy plays, not automatic Normal/Best Bet value.",qcTitle:"US OPEN QUICKIES — SATURDAY, SEPTEMBER 5",qcs:tennisQ},

    UFC:{icon:"🥊",meta:"UFC PARIS • SEPTEMBER 5, 2026 • WEIGH-INS COMPLETE",kicker:"UFC PARIS QUICKIE",title:"UFC",description:"UFC Paris is active today at Accor Arena. Official weigh-ins are complete; prelims begin 12:00 ET / 9:00 PT and main card 3:00 ET / 12:00 PT. Current official winner odds populate only verified bouts.",chips:[["EVENT TODAY","green"],["WEIGH-INS COMPLETE","purple"],["NO INVENTED METHOD PROPS","gold"]],hotTop:[["Salahdine Parnasse","Fight winner • -550","84%","Main-event favorite; Dan Hooker +400."],["Nathaniel Wood","Fight winner • -315","76%","Late replacement Pavel Andrusca adds volatility."],["Mario Pinto","Fight winner • -305","75%","Strong prelim favorite."],["Oumar Sy","Fight winner • -230","69%","Solid favorite."],["Felipe Lima","Fight winner • -185","65%","Moderate favorite."],["Farès Ziam","Fight winner • -150","59%","Co-main favorite but not SNS-grade."]],winners:[["Hooker vs Parnasse","Parnasse","84%","-550"],["Ziam vs Sola","Ziam","59%","-150"],["Wood vs Andrusca","Wood","76%","-315"],["Pinto vs Spann","Pinto","75%","-305"],["Sy vs Bukauskas","Sy","69%","-230"],["Charriere vs Lima","Lima","65%","-185"]],twenty:ufc20,twentyNote:"Official UFC moneylines are used. Method/round props remain WATCH unless independently verified in a later refresh.",qcTitle:"PER-FIGHT QUICKIES — UFC PARIS",qcs:ufcFights},

    Boxing:{icon:"🥊",meta:"BOXING • SEPTEMBER 5, 2026 • CROKE PARK",kicker:"BOXING EVENT QUICKIE",title:"BOXING",description:"Katie Taylor vs Flora Pili is the active headline event today at Croke Park in Dublin. Taylor and Pili made weight; ring walk is expected around 10:00 PM Irish/UK time (about 2:00 PM PT), subject to undercard timing.",chips:[["EVENT TODAY","green"],["WEIGH-IN VERIFIED","purple"],["CURRENT MARKETS","gold"]],hotTop:[["Katie Taylor","Fight winner • 1.04 / about -2500","94%","Accuracy-first only; extremely poor price efficiency."],["Katie Taylor","Win by decision • 1.44 / about -227","76%","Preferred probability-to-price expression; Taylor has repeatedly gone the distance."]],winners:[["Katie Taylor vs Flora Pili","Katie Taylor","94%","Taylor 1.04 / Pili 15.0"]],twenty:boxing20,twentyNote:"Current Paddy Power market plus current fight previews. Promotional boosted odds are excluded from L&J pricing.",qcTitle:"PER-FIGHT QUICKIES — TAYLOR vs PILI",qcs:[q("Expected ring walk ~10:00 PM Irish/UK • ~2:00 PT","KATIE TAYLOR","FLORA PILI","Taylor 1.04 / Pili 15.0 • Taylor decision 1.44","Katie Taylor","94%",["Taylor ML • 94%","Taylor by decision • 76%"],["Taylor ML • 94%"],["Taylor by decision • 76%"],["Taylor by decision • 76%"],W(),"Main-event ring time can slide with the undercard. Taylor's low stoppage profile makes decision the preferred value channel over a forced KO prop.")]},

    FIBA_Women:{icon:"🌍🏀",meta:"FIBA WOMEN • WORLD CUP • SEPTEMBER 5, 2026",kicker:"FIBA WOMEN WORLD CUP",title:"FIBA WOMEN",description:"Day 2 in Berlin follows next-game-only logic. Earlier September 5 games close as they start; the remaining upcoming game stays actionable only if current markets are verified.",chips:[["WORLD CUP ACTIVE","green"],["NEXT-GAME LOGIC","purple"],["NO STALE PROPS","gold"]],hotTop:[],winners:[["Mali vs Spain","CLOSED/LIVE","—","09:30 Berlin"],["Nigeria vs Hungary","CLOSED/LIVE","—","12:15 Berlin"],["Germany vs Japan","CLOSED/LIVE","—","16:00 Berlin"],["France vs Korea","France lean / market WATCH","78%","18:45 Berlin • 9:45 PT"]],twenty:[],twentyNote:"No current independently verified player-prop board cleared the morning gate.",qcTitle:"FIBA WOMEN — SEPTEMBER 5",qcs:[q("09:30 Berlin • CLOSED/LIVE","MALI","SPAIN","Pregame market closed","CLOSED/LIVE","—",w(CLOSED),w(CLOSED),w(CLOSED),w(CLOSED),w(CLOSED),"No backfill after start."),q("12:15 Berlin • CLOSED/LIVE","NIGERIA","HUNGARY","Pregame market closed","CLOSED/LIVE","—",w(CLOSED),w(CLOSED),w(CLOSED),w(CLOSED),w(CLOSED),"No backfill after start."),q("16:00 Berlin • CLOSED/LIVE","GERMANY","JAPAN","Pregame market closed","CLOSED/LIVE","—",w(CLOSED),w(CLOSED),w(CLOSED),w(CLOSED),w(CLOSED),"No backfill after start."),q("18:45 Berlin • 12:45 ET / 9:45 PT","FRANCE","KOREA","Current executable market WATCH","France lean","78%",W(),W(),W(),W(),W(),"France entered Day 2 as a leading contender; without a verified executable line, this remains a prediction lean rather than a bet.")]},

    WNBA:{icon:"🏀",meta:"WNBA • WORLD CUP BREAK • NEXT GAMES SEPTEMBER 17",kicker:"WNBA STATUS",title:"WNBA",description:"WNBA regular-season play is paused for the FIBA Women’s World Cup and resumes September 17. No stale pre-break player props are carried forward.",chips:[["LEAGUE PAUSED","purple"],["RESUMES SEP 17","gold"],["MARKET WATCH","green"]],hotTop:[],winners:[],twenty:[],twentyNote:"No current WNBA player markets are published during the World Cup break.",qcTitle:"NEXT ANNOUNCED WNBA GAMES — SEPTEMBER 17",qcs:[q("SEP 17 • 8:00 ET / 5:00 PT","WASHINGTON","CHICAGO","Early market WATCH","WATCH","—",W(),W(),W(),W(),W(),"Do not project a live line this far out."),q("SEP 17 • 8:00 ET / 5:00 PT","LOS ANGELES","DALLAS","Early market WATCH","WATCH","—",W(),W(),W(),W(),W(),"Dallas resumes after World Cup break; role/availability must be re-checked."),q("SEP 17 • 10:00 ET / 7:00 PT","PHOENIX","PORTLAND","Early market WATCH","WATCH","—",W(),W(),W(),W(),W(),"Market activation gate."),q("SEP 17 • 10:00 ET / 7:00 PT","LAS VEGAS","SEATTLE","Early market WATCH","WATCH","—",W(),W(),W(),W(),W(),"Market activation gate.")]},

    NFL:{icon:"🏈",meta:"NFL • WEEK 1 EARLY BOARD • SEPTEMBER 5 REFRESH",kicker:"NFL WEEK 1 QUICKIE",title:"NFL",description:"Preseason is complete. Every Week 1 game from Wednesday September 9 through Monday September 14 remains staged in the locked QC format. Current team lines are early-cycle; player props stay WATCH until verified.",chips:[["WEEK 1 NEXT","green"],["16 GAME QCs","purple"],["PLAYER PROP GATE","gold"]],hotTop:[],winners:[["NE @ SEA","Seahawks","64%","SEA -3.5 consensus"],["SF vs LAR (Melbourne)","Rams","61%","LAR -2.5 to -3.5"],["NO @ DET","Lions","68%","DET -7"],["ARI @ LAC","Chargers","75%","LAC -9.5 to -11.5"],["WAS @ PHI","Eagles","65%","PHI -4.5 to -5.5"]],twenty:[],twentyNote:"No current Week 1 player prop is promoted from preseason or early forecast memory. Exact posted player markets will populate in the next refreshes.",qcTitle:"NFL WEEK 1 — EVERY GAME",qcs:nflQ},

    NBA:{icon:"🏀",meta:"NBA • OFFSEASON • SEPTEMBER 5, 2026",kicker:"NBA STATUS",title:"NBA",description:"NBA is in the offseason. No stale prediction slate is displayed; current game/prop coverage activates when preseason or regular-season games and markets are available.",chips:[["OFFSEASON","purple"],["NO STALE PROPS","gold"]],hotTop:[],winners:[],twenty:[],twentyNote:"Offseason status — 20 Piece remains empty by design.",qcTitle:"SEASON START / OFFSEASON STATUS",qcs:[q("OFFSEASON","NBA","SEASON","No current game market","OFFSEASON","—",W(),W(),W(),W(),W(),"Next active slate will replace this status when verified.")]},
    NHL:{icon:"🏒",meta:"NHL • OFFSEASON • SEPTEMBER 5, 2026",kicker:"NHL STATUS",title:"NHL",description:"NHL regular-season play has not begun. No prior-day or preseason market is carried into the current publication.",chips:[["OFFSEASON","purple"],["NO STALE PROPS","gold"]],hotTop:[],winners:[],twenty:[],twentyNote:"Offseason status — current player markets unavailable.",qcTitle:"SEASON START / OFFSEASON STATUS",qcs:[q("OFFSEASON","NHL","SEASON","No current game market","OFFSEASON","—",W(),W(),W(),W(),W(),"Activate when an official game slate and markets are current.")]},
    NCAA_Basketball:{icon:"🏀",meta:"NCAA BASKETBALL • OFFSEASON • SEPTEMBER 5, 2026",kicker:"NCAA BASKETBALL STATUS",title:"NCAA BASKETBALL",description:"College basketball is not in an active game-market window. Stale prior content has been removed.",chips:[["OFFSEASON","purple"],["MARKET WATCH","gold"]],hotTop:[],winners:[],twenty:[],twentyNote:"No current player board.",qcTitle:"SEASON START / OFFSEASON STATUS",qcs:[q("OFFSEASON","NCAA","BASKETBALL","No current market","OFFSEASON","—",W(),W(),W(),W(),W(),"Activate on the first verified slate.")]},
    FIBA_Men:{icon:"🌍🏀",meta:"FIBA MEN • NEXT EVENT WATCH • SEPTEMBER 5, 2026",kicker:"FIBA MEN STATUS",title:"FIBA MEN",description:"No September 5 FIBA Men event was independently verified in the morning source sweep. The page is explicitly placed on next-announced-event WATCH rather than retaining stale prior-window content.",chips:[["NO GAME TODAY","purple"],["NEXT EVENT WATCH","gold"]],hotTop:[],winners:[],twenty:[],twentyNote:"No current men’s FIBA player markets.",qcTitle:"NEXT ANNOUNCED EVENT STATUS",qcs:[q("NEXT EVENT — VERIFY","FIBA MEN","CALENDAR","Market WATCH","WATCH","—",W(),W(),W(),W(),W(),"Exact next event/game must be confirmed before a prediction is published.")]}
  };

  const global20=[...tennis20,...ufc20,...mlb20,...cfb20,...boxing20].sort((a,b)=>parseInt(b[4])-parseInt(a[4])).slice(0,20);
  const home={meta:"LEGZ & JINX • SATURDAY, SEPTEMBER 5, 2026 • 9:00 AM PT REFRESH",kicker:"INDEPENDENT DAILY ISSUE",title:"LEGZ & JINX DAILY PREDICTIONS",description:"Day-of publication refreshed for September 5. MLB, NCAA Football, US Open Tennis, UFC Paris, FIBA Women and Katie Taylor–Flora Pili are active today; inactive leagues are explicitly placed in next-event or offseason states. No stale September 3 slate remains in the data layer.",chips:[["SEP 5 CURRENT SLATE","green"],["QC LAYOUT LOCKED","purple"],["CURRENT MARKETS ONLY","gold"]],hotTop:[["Coco Gauff","US Open match winner • -2500 to -3300","93%","High raw hit confidence; poor price efficiency."],["Katie Taylor","Fight winner • 1.04 / about -2500","94%","Highest raw hit confidence; preferred value expression is decision."],["Taylor Fritz","US Open match winner • -680 to -700","86%","Strong favorite."],["Salahdine Parnasse","UFC Paris winner • -550","84%","Main-event favorite."],["Parker Messick","MLB O6.5 K • +114","64%","Best current MLB probability-to-price prop."],["Mason McKenzie","CFB U184.5 pass yds • -114","64%","Best current verified CFB player threshold."]],winners:[["UFC Paris: Hooker vs Parnasse","Parnasse","84%","-550"],["Boxing: Taylor vs Pili","Katie Taylor","94%","1.04"],["US Open: Bucsa vs Gauff","Gauff","93%","-2500 to -3300"],["MLB: MIL @ CIN","Brewers","69%","-162"],["MLB: LAA @ PIT","Pirates","68%","-178"],["CFB: Clemson @ LSU","LSU","66%","-9.5"]],twenty:global20,twentyNote:"Global 20 Piece is drawn only from current verified player/participant markets across active sports. One participant counts once; weaker duplicate expressions are suppressed."};
  return {nav,sports,home,updated:"September 5, 2026 • 9:00 AM PT refresh"};
})();
