/* LEGZ & JINX — L&J LIVE PREDICTIONS DATA
   September 8, 2026 • 12:00 PM PT live refresh.
   LIVE DATA ONLY. No stale completed-event filler. No invented score, clock, line or prop. */
window.LJ_LIVE_DATA = (() => {
  const WATCH="WATCH — exact current live market/state not independently synchronized";
  const MODEL="MODEL-ONLY FINISH FORECAST — not an executable sportsbook line";
  const nav=[["MLB","⚾","LJ_Live_MLB.html"],["NFL","🏈","LJ_Live_NFL.html"],["NBA","🏀","LJ_Live_NBA.html"],["WNBA","🏀","LJ_Live_WNBA.html"],["NHL","🏒","LJ_Live_NHL.html"],["FIBA MEN","🌍🏀","LJ_Live_FIBA_Men.html"],["FIBA WOMEN","🌍🏀","LJ_Live_FIBA_Women.html"],["NCAA FOOTBALL","🏈","LJ_Live_NCAA_Football.html"],["NCAA BASKETBALL","🏀","LJ_Live_NCAA_Basketball.html"],["TENNIS","🎾","LJ_Live_Tennis.html"],["UFC","🥊","LJ_Live_UFC.html"],["BOXING","🥊","LJ_Live_Boxing.html"]];
  const empty=(icon,title,detail)=>({icon,title,meta:`${title} • SEP 8 • 12:00 PM PT`,kicker:`${title} LIVE`,description:detail,chips:[["NO VERIFIED LIVE EVENT","purple"],["WATCH","gold"],["NO STALE FILLER","gold"]],hotTop:[],winners:[],twenty:[],twentyNote:"No current live selection clears the verification gate.",qcTitle:`${title} — LIVE QUICKIES`,qcs:[]});
  const sports={
    MLB:empty("⚾","MLB","No MLB game is independently verified in progress. Connected StatsHawk returned no in-progress September 8 game and DraftKings returned no competition in the current live window."),
    NFL:empty("🏈","NFL","No NFL game is independently verified in progress. Connected StatsHawk returned no in-progress September 8 contest."),
    NBA:empty("🏀","NBA","No NBA game is independently verified in progress. Connected StatsHawk returned no in-progress September 8 contest."),
    WNBA:empty("🏀","WNBA","No WNBA league game is independently verified in progress. Connected StatsHawk returned no in-progress September 8 contest."),
    NHL:empty("🏒","NHL","No NHL game is independently verified in progress. Connected StatsHawk returned no in-progress September 8 contest."),
    FIBA_Men:empty("🌍🏀","FIBA MEN","No monitored senior men's FIBA event is independently verified in progress at this sweep."),
    FIBA_Women:empty("🌍🏀","FIBA WOMEN","Germany-Korea is inside its scheduled September 8 game window, but FIBA's official game center still reports Live (0) and no synchronized independent exact score/state cleared verification. Hungary-Japan is no longer carried as an active-live candidate. FIBA Women remains WATCH; no score, player line, winner lean, finish forecast or executable market is published."),
    NCAA_Football:empty("🏈","NCAA FOOTBALL","No NCAA Football game is independently verified in progress. Connected StatsHawk returned no in-progress September 8 contest."),
    NCAA_Basketball:empty("🏀","NCAA BASKETBALL","No NCAA Basketball game is independently verified in progress. Connected StatsHawk returned no in-progress September 8 contest."),
    Tennis:{icon:"🎾",title:"TENNIS",meta:"TENNIS • SEP 8 • 12:00 PM PT",kicker:"TENNIS LIVE",description:"US Open men's quarterfinal — Frances Tiafoe vs Alex Michelsen — is independently verified in progress by current Guardian live coverage and Sky Sports' on-now listing. Their accessible snapshots do not synchronize the exact game/point score, so L&J publishes the verified LIVE state but withholds the exact score, current player-stat line and all executable in-play markets. The L&J winner lean below is MODEL-ONLY and is not a sportsbook line.",chips:[["1 VERIFIED LIVE MATCH","green"],["EXACT SCORE WITHHELD","gold"],["MODEL-ONLY LEAN","purple"]],hotTop:[["Frances Tiafoe","MODEL-ONLY winner lean • 60%","60%","Not score-adjusted. Built from verified pre-match pricing/form context while exact live game state remains unsynchronized; not an executable sportsbook line."]],winners:[["US OPEN QF • LIVE","Frances Tiafoe — MODEL-ONLY lean","60%","Exact live score/market withheld; not an executable sportsbook line"]],twenty:[],twentyNote:"No live player-prop or statistical-finish card is published because exact current point/game state and player live statistics are not independently synchronized.",qcTitle:"TENNIS — LIVE QUICKIE",qcs:[{time:"SEP 8 • LIVE",away:"ALEX MICHELSEN",home:"FRANCES TIAFOE",market:"LIVE MATCH VERIFIED • exact score and executable in-play market withheld",winner:"Tiafoe — MODEL-ONLY lean",conf:"60%",hot:["Tiafoe model-only winner lean • 60% • NOT an executable sportsbook line"],sns1:[],sns2:[],normal:[],demon:[],foot:"Guardian and Sky independently verify the match is underway. Exact score/game state, player live stats, injury/availability change, statistical finish ranges and in-play prices are withheld because synchronized independent verification is unavailable at this snapshot."}]},
    UFC:empty("🥊","UFC","No UFC/DWCS bout is independently verified in progress. Dana White's Contender Series Week 5 begins at 4:00 PM PT and remains WATCH until a specific bout is verified active."),
    Boxing:empty("🥊","BOXING","No monitored boxing bout is independently verified in progress at this sweep; no schedule-only fight is promoted as LIVE.")
  };
  const statuses=[["MLB","NO LIVE EVENT","StatsHawk + DraftKings: no verified in-progress game"],["NFL","NO LIVE EVENT","StatsHawk: no verified in-progress game"],["NBA","NO LIVE EVENT","StatsHawk: no verified in-progress game"],["WNBA","NO LIVE EVENT","StatsHawk: no verified in-progress game"],["NHL","NO LIVE EVENT","StatsHawk: no verified in-progress game"],["FIBA_Men","NO LIVE EVENT","No monitored senior men's event verified live"],["FIBA_Women","WATCH","Germany-Korea inside scheduled window; FIBA still reports Live (0); exact state withheld"],["NCAA_Football","NO LIVE EVENT","StatsHawk: no verified in-progress game"],["NCAA_Basketball","NO LIVE EVENT","StatsHawk: no verified in-progress game"],["Tennis","LIVE","Tiafoe-Michelsen independently verified underway; exact score/market withheld"],["UFC","WATCH","DWCS starts 4:00 PM PT; no bout verified active now"],["Boxing","NO LIVE EVENT","No bout independently verified live"]];
  const home={meta:"L&J LIVE • SEPTEMBER 8, 2026 • 12:00 PM PT",kicker:"L&J LIVE PREDICTIONS",title:"LEGZ & JINX — LIVE PREDICTIONS",description:"One monitored event clears the strict active-live gate: Frances Tiafoe vs Alex Michelsen at the U.S. Open. Two independent current sources confirm the quarterfinal is underway, but their accessible snapshots do not synchronize the exact game/point score, so L&J withholds the score, live player-stat line and executable in-play markets. Connected league feeds show no active MLB, NFL, NBA, WNBA, NHL, NCAA Football or NCAA Basketball game. Germany-Korea is inside its FIBA Women scheduled window but remains WATCH because FIBA still reports Live (0) and no synchronized independent state cleared verification. UFC/DWCS begins later today.",chips:[["1 VERIFIED LIVE EVENT","green"],["TENNIS LIVE","purple"],["NO FABRICATED SCORE / LINE / PROP","gold"]],hotTop:[["Frances Tiafoe","MODEL-ONLY winner lean • 60%","60%","Not an executable sportsbook line; exact live score is withheld."]],winners:[["US OPEN QF • LIVE","Frances Tiafoe — MODEL-ONLY lean","60%","Exact live score/market withheld"]],twenty:[],twentyNote:"No statistical finish forecast beyond the labeled model-only winner lean is displayed because synchronized exact live state is unavailable."};
  return {updated:"SEP 8, 2026 • 12:00 PM PT LIVE SNAPSHOT",nav,sports,statuses,home,WATCH,MODEL};
})();