/* LEGZ & JINX — L&J LIVE PREDICTIONS DATA
   September 8, 2026 • 2:00 PM PT live refresh.
   LIVE DATA ONLY. No stale completed-event filler. No invented score, clock, line or prop. */
window.LJ_LIVE_DATA = (() => {
  const WATCH="WATCH — exact current live market/state not independently synchronized";
  const MODEL="MODEL-ONLY FINISH FORECAST — not an executable sportsbook line";
  const nav=[["MLB","⚾","LJ_Live_MLB.html"],["NFL","🏈","LJ_Live_NFL.html"],["NBA","🏀","LJ_Live_NBA.html"],["WNBA","🏀","LJ_Live_WNBA.html"],["NHL","🏒","LJ_Live_NHL.html"],["FIBA MEN","🌍🏀","LJ_Live_FIBA_Men.html"],["FIBA WOMEN","🌍🏀","LJ_Live_FIBA_Women.html"],["NCAA FOOTBALL","🏈","LJ_Live_NCAA_Football.html"],["NCAA BASKETBALL","🏀","LJ_Live_NCAA_Basketball.html"],["TENNIS","🎾","LJ_Live_Tennis.html"],["UFC","🥊","LJ_Live_UFC.html"],["BOXING","🥊","LJ_Live_Boxing.html"]];
  const empty=(icon,title,detail)=>({icon,title,meta:`${title} • SEP 8 • 2:00 PM PT`,kicker:`${title} LIVE`,description:detail,chips:[["NO VERIFIED LIVE EVENT","purple"],["WATCH","gold"],["NO STALE FILLER","gold"]],hotTop:[],winners:[],twenty:[],twentyNote:"No current live selection clears the verification gate.",qcTitle:`${title} — LIVE QUICKIES`,qcs:[]});
  const sports={
    MLB:empty("⚾","MLB","No MLB game is independently verified in progress. Connected StatsHawk returned no in-progress September 8 game; DraftKings shows the current-window MLB slate as upcoming, not live."),
    NFL:empty("🏈","NFL","No NFL game is independently verified in progress. Connected StatsHawk returned no in-progress September 8 contest."),
    NBA:empty("🏀","NBA","No NBA game is independently verified in progress. Connected StatsHawk returned no in-progress September 8 contest."),
    WNBA:empty("🏀","WNBA","No WNBA league game is independently verified in progress. Connected StatsHawk returned no in-progress September 8 contest."),
    NHL:empty("🏒","NHL","No NHL game is independently verified in progress. Connected StatsHawk returned no in-progress September 8 contest."),
    FIBA_Men:empty("🌍🏀","FIBA MEN","No monitored senior men's FIBA event is independently verified in progress at this sweep."),
    FIBA_Women:empty("🌍🏀","FIBA WOMEN","No FIBA Women's Basketball World Cup game is currently live. The official FIBA game center reports Live (0); completed September 8 games are not carried as active-live content."),
    NCAA_Football:empty("🏈","NCAA FOOTBALL","No NCAA Football game is independently verified in progress. Connected StatsHawk returned no in-progress September 8 contest."),
    NCAA_Basketball:empty("🏀","NCAA BASKETBALL","No NCAA Basketball game is independently verified in progress. Connected StatsHawk returned no in-progress September 8 contest."),
    Tennis:empty("🎾","TENNIS","No monitored U.S. Open singles match is independently verified in progress at this snapshot. Alex Michelsen vs Frances Tiafoe is complete and has been removed from active-live presentation. The September 8 night session begins later; schedule-only matches are not promoted as LIVE."),
    UFC:empty("🥊","UFC","No UFC/DWCS bout is independently verified in progress. Dana White's Contender Series Week 5 is scheduled to begin at 4:00 PM PT and remains WATCH until a specific bout is verified active."),
    Boxing:empty("🥊","BOXING","No monitored boxing bout is independently verified in progress at this sweep; no schedule-only fight is promoted as LIVE.")
  };
  const statuses=[["MLB","NO LIVE EVENT","StatsHawk: none in progress; DraftKings current-window games upcoming"],["NFL","NO LIVE EVENT","StatsHawk: no verified in-progress game"],["NBA","NO LIVE EVENT","StatsHawk: no verified in-progress game"],["WNBA","NO LIVE EVENT","StatsHawk: no verified in-progress game"],["NHL","NO LIVE EVENT","StatsHawk: no verified in-progress game"],["FIBA_Men","NO LIVE EVENT","No monitored senior men's event verified live"],["FIBA_Women","NO LIVE EVENT","Official FIBA game center: Live (0)"],["NCAA_Football","NO LIVE EVENT","StatsHawk: no verified in-progress game"],["NCAA_Basketball","NO LIVE EVENT","StatsHawk: no verified in-progress game"],["Tennis","WATCH","Tiafoe-Michelsen completed; night session has not begun"],["UFC","WATCH","DWCS starts 4:00 PM PT; no bout verified active now"],["Boxing","NO LIVE EVENT","No bout independently verified live"]];
  const home={meta:"L&J LIVE • SEPTEMBER 8, 2026 • 2:00 PM PT",kicker:"L&J LIVE PREDICTIONS",title:"LEGZ & JINX — LIVE PREDICTIONS",description:"No monitored event clears the strict active-live gate at this snapshot. The prior Tiafoe-Michelsen tennis card is closed after Michelsen's completed 7-5, 6-3, 6-3 win and has been removed from active-live presentation. Connected feeds show no active MLB, NFL, NBA, WNBA, NHL, NCAA Football or NCAA Basketball game; official FIBA reports Live (0). The U.S. Open night session and UFC/DWCS action are upcoming, not live. No executable line, live prop, score, player state, injury update, winner lean or finish forecast is displayed without a verified live event.",chips:[["NO VERIFIED LIVE EVENT","purple"],["WATCH NEXT STARTS","gold"],["NO FABRICATED SCORE / LINE / PROP","gold"]],hotTop:[],winners:[],twenty:[],twentyNote:"No statistical finish forecast is displayed because no monitored event is independently verified in progress."};
  return {updated:"SEP 8, 2026 • 2:00 PM PT LIVE SNAPSHOT",nav,sports,statuses,home,WATCH,MODEL};
})();