/* LEGZ & JINX — MATERIAL CHANGE ALERT FEED
   Maintained by the L&J Material Change Watch. Only active, re-analysis-worthy
   items belong here. The Daily Home renderer groups them by league and drops
   records automatically after expiresAt. */
window.LJ_MATERIAL_ALERTS = {
  updated: "September 18, 2026 • 5:58 AM PT",
  alerts: [
    {league:"NFL",game:"Seahawks at Cardinals — Sep 20",summary:"Sam Darnold is OUT and Drew Lock will start for Seattle.",impact:"Rebuild Seattle passing, receiver, team-total and game-winner projections around Lock.",urgency:"High",status:"CONFIRMED",source:"https://www.seahawks.com/news/sam-darnold-ruled-out-for-seahawks-week-2-game-at-arizona-drew-lock-will-start",expiresAt:"2026-09-21T00:30:00Z"},
    {league:"NFL",game:"Falcons vs. Panthers — Sep 20",summary:"Tua Tagovailoa did not practice with an oblique injury; Atlanta has not named its starter.",impact:"Keep Falcons passing props, team total and moneyline provisional; model Rush and Penix as the principal alternatives.",urgency:"High",status:"CONFIRMED INJURY / STARTER UNRESOLVED",source:"https://www.atlantafalcons.com/news/falcons-not-ruling-anyone-out-qb-panthers-michael-penix-tua-tagovailoa",expiresAt:"2026-09-21T00:30:00Z"},
    {league:"NFL",game:"Vikings at Bears — Sep 20",summary:"Jordan Mason is on injured reserve; Kyler Murray remains in concussion protocol.",impact:"Raise Aaron Jones' workload range and retain separate Murray/Wentz projections for every Minnesota offensive market.",urgency:"High",status:"CONFIRMED / QB STATUS UNRESOLVED",source:"https://www.vikings.com/news/injury-report-week-2-chicago-bears-2026",expiresAt:"2026-09-21T04:30:00Z"},
    {league:"NFL",game:"Bengals vs. Texans — Sep 20",summary:"Joe Burrow was limited Thursday with back soreness; Houston WR Nico Collins did not practice Thursday and his availability is unresolved.",impact:"Keep Burrow passing/rushing overs and Bengals receiver props cautious. Make Collins props, C.J. Stroud passing output, Houston receiver distribution and Bengals defensive projections conditional on Friday status.",urgency:"High",status:"CONFIRMED PRACTICE REPORT / AVAILABILITY UNRESOLVED",source:"https://www.nfl.com/injuries/league/2026/reg2",expiresAt:"2026-09-21T23:59:00Z"},
    {league:"NFL",game:"Saints at Ravens — Sep 20",summary:"Zay Flowers, LT Ronnie Stanley and LG John Simpson missed practice again Thursday; Flowers is day to day with a hamstring injury. Saints WR Chris Olave was limited Thursday by a hamstring injury.",impact:"Keep Flowers and Olave props provisional; downgrade Baltimore protection and passing efficiency if Stanley or Simpson sits, and prepare elevated Rashod Bateman/Devontez Walker target scenarios if Flowers is inactive.",urgency:"High",status:"CONFIRMED PRACTICE REPORT / AVAILABILITY UNRESOLVED",source:"https://www.baltimoreravens.com/news/ravens-injury-report-zay-flowers-ronnie-stanley-john-simpson-practice-report-saints-2026",expiresAt:"2026-09-20T23:30:00Z"},
    {league:"MLB",game:"Yankees at Diamondbacks — Sep 18",summary:"Aaron Judge left Wednesday's game with lower-leg tightness; next-game availability remains unresolved.",impact:"Keep Judge props and Yankees offensive overs provisional until the confirmed lineup is posted.",urgency:"High",status:"CONFIRMED INJURY / AVAILABILITY UNRESOLVED",source:"https://www.mlb.com/news/baseball-injury-updates",expiresAt:"2026-09-19T06:00:00Z"},
    {league:"MLB",game:"Tigers at White Sox — Sep 18",summary:"Detroit placed closer Kyle Finnegan on the 15-day injured list with left groin inflammation.",impact:"Remove Finnegan save and relief props, downgrade Detroit's late-inning bullpen projection, and reassess the full-game moneyline, run line and total; Chicago's late scoring probability rises until Detroit establishes a replacement closer.",urgency:"High",status:"CONFIRMED IL TRANSACTION",source:"https://www.mlb.com/news/baseball-injury-updates",expiresAt:"2026-09-19T04:00:00Z"}
  ]
};
