/* LEGZ & JINX — MATERIAL CHANGE ALERT FEED
   Maintained by the L&J Material Change Watch. Only active, re-analysis-worthy
   items belong here. The Daily Home renderer groups them by league and drops
   records automatically after expiresAt. */
window.LJ_MATERIAL_ALERTS = {
  updated: "September 18, 2026 • 6:28 PM PT",
  alerts: [
    {league:"NFL",game:"Raiders at Chargers — Sep 20",summary:"Las Vegas lists TE Brock Bowers doubtful after a limited Friday practice. The Chargers list WR Ladd McConkey questionable and starting G/T Trey Pipkins III out.",impact:"Treat Bowers as unlikely to play: remove or sharply downgrade his props, redistribute Raiders targets and lower Kirk Cousins passing efficiency. Keep McConkey props conditional through inactives and reduce Chargers protection grading without Pipkins.",urgency:"High",status:"CONFIRMED FINAL DESIGNATIONS",source:"https://www.raiders.com/news/las-vegas-raiders-los-angeles-chargers-nfl-week-2-injury-report-2026-season",expiresAt:"2026-09-21T00:30:00Z"},
    {league:"NFL",game:"Seahawks at Cardinals — Sep 20",summary:"Sam Darnold is OUT and Drew Lock will start for Seattle.",impact:"Rebuild Seattle passing, receiver, team-total and game-winner projections around Lock.",urgency:"High",status:"CONFIRMED",source:"https://www.seahawks.com/news/sam-darnold-ruled-out-for-seahawks-week-2-game-at-arizona-drew-lock-will-start",expiresAt:"2026-09-21T00:30:00Z"},
    {league:"NFL",game:"Giants at Rams — Sep 21",summary:"Aaron Donald says the plan is to make his season debut Monday after missing Week 1; Myles Garrett remains on injured reserve following knee surgery.",impact:"Upgrade the Rams interior-pressure and run-defense projections, lower Giants passing-efficiency and rushing ceilings, and reassess Jaxson Dart passing, Cam Skattebo rushing, sack props, the Giants team total and Rams moneyline. Retain snap-limit sensitivity because Donald has not played since 2023.",urgency:"High",status:"CREDIBLE PLAYER CONFIRMATION / FINAL STATUS PENDING",source:"https://www.nfl.com/news/rams-aaron-donald-plans-to-play-monday-night-vs-giants",expiresAt:"2026-09-22T05:30:00Z"},
    {league:"NFL",game:"Falcons vs. Panthers — Sep 20",summary:"Atlanta confirmed Cooper Rush will start, with Jack Strand as backup. Michael Penix Jr. is out and Tua Tagovailoa is doubtful.",impact:"Remove all alternate-starter branches and build Atlanta around Rush. Downgrade deep-passing efficiency and Falcons receiver ceilings, increase Bijan Robinson rushing and short-target volume, and reassess Carolina defensive props.",urgency:"High",status:"CONFIRMED RUSH STARTING",source:"https://www.nfl.com/news/falcons-qb-cooper-rush-start-week-2-panthers",expiresAt:"2026-09-21T00:30:00Z"},
    {league:"NFL",game:"Vikings at Bears — Sep 20",summary:"Minnesota ruled Kyler Murray and WR Jauan Jennings out; Carson Wentz will start. Starting RT Brian O'Neill is questionable. Jordan Mason remains on injured reserve.",impact:"Replace every Murray-based projection with Wentz; remove Murray and Jennings props, lower Minnesota quarterback-rushing output and redistribute receiver targets. Retain a protection downgrade if O'Neill is inactive and raise Aaron Jones' workload range without Mason.",urgency:"High",status:"CONFIRMED FINAL DESIGNATIONS / WENTZ STARTING",source:"https://www.vikings.com/news/injury-report-week-2-chicago-bears-2026",expiresAt:"2026-09-21T04:30:00Z"},
    {league:"NFL",game:"Bengals vs. Texans — Sep 20",summary:"Houston ruled WR Nico Collins out with a hamstring injury. Bengals coach Zac Taylor confirmed Joe Burrow is good to go and will start after a full Friday practice, despite his official questionable designation.",impact:"Remove Collins props, reduce C.J. Stroud's passing and Houston team-total ceilings, and redistribute Texans targets. Restore Burrow as Cincinnati's starting baseline while retaining a modest back-soreness sensitivity for mobility and rushing props.",urgency:"High",status:"CONFIRMED COLLINS OUT / BURROW STARTING",source:"https://www.nfl.com/news/bengals-joe-burrow-texans-back-injury",expiresAt:"2026-09-21T23:59:00Z"},
    {league:"NFL",game:"Saints at Ravens — Sep 20",summary:"Baltimore lists Zay Flowers doubtful; LT Ronnie Stanley and LG John Simpson are questionable. New Orleans lists Chris Olave questionable after limited practices Thursday and Friday.",impact:"Treat Flowers as unlikely to play, remove or sharply downgrade his props, and raise Rashod Bateman plus secondary-receiver target shares. Maintain protection downgrades if Stanley or Simpson sits. Keep Olave and Saints passing projections conditional through inactives.",urgency:"High",status:"CONFIRMED FINAL DESIGNATIONS",source:"https://www.baltimoreravens.com/news/injury-report-zay-flowers-ravens-saints-ronnie-stanley-john-simpson-trey-hendrickson-week-2",expiresAt:"2026-09-20T23:30:00Z"},
    {league:"MLB",game:"Phillies at Mets — Sep 18",summary:"Phillies reliever Jonathan Bowlan exited Thursday with right-groin tightness, further thinning an already strained late-inning bullpen.",impact:"Downgrade Philadelphia late-inning run prevention and reassess the full-game moneyline, run line and total; first-five markets are less affected than full-game markets.",urgency:"High",status:"CONFIRMED INJURY / AVAILABILITY UNRESOLVED",source:"https://www.mlb.com/news/jonathan-bowlan-exits-with-right-groin-injury",expiresAt:"2026-09-19T03:00:00Z"},
    {league:"MLB",game:"Yankees — upcoming games",summary:"The Yankees announced Aaron Judge will be placed on the 10-day injured list Saturday with a right calf strain; the move is expected to be retroactive to September 17.",impact:"Remove Judge props and downgrade New York power, team-total and run-production projections for the remaining regular-season games. Redistribute lineup protection, runs and RBI opportunities among Paul Goldschmidt, Cody Bellinger, Heliot Ramos and Ben Rice.",urgency:"High",status:"CONFIRMED TEAM ANNOUNCEMENT / IL TRANSACTION PENDING SATURDAY",source:"https://www.reuters.com/sports/yankees-place-aaron-judge-calf-10-day-il--flm-2026-09-18/",expiresAt:"2026-09-28T07:00:00Z"},
    {league:"MLB",game:"Tigers at White Sox — Sep 18",summary:"Detroit placed closer Kyle Finnegan on the 15-day injured list with left groin inflammation.",impact:"Remove Finnegan save and relief props, downgrade Detroit's late-inning bullpen projection, and reassess the full-game moneyline, run line and total; Chicago's late scoring probability rises until Detroit establishes a replacement closer.",urgency:"High",status:"CONFIRMED IL TRANSACTION",source:"https://www.mlb.com/news/baseball-injury-updates",expiresAt:"2026-09-19T04:00:00Z"}
  ]
};
