/* L&J 12PM PT MIDDAY REFRESH — SEP 17 2026. DAILY ONLY; L&J LIVE REMAINS PAUSED. */
(()=>{const D=window.LJ_DATA;if(!D?.sports)return;const W='WATCH / NO BET — current market or prediction has not cleared L&J quality gate';const Q=(t,a,h,w,c,m,hot=[W],foot='Sep 17 noon refresh; verify exact price immediately before entry.')=>({time:t,away:a,home:h,market:m,winner:w,conf:c,hot,sns1:[W],sns2:[W],normal:hot,demon:[W],foot});const rows=s=>(s.qcs||[]).filter(q=>q.winner&&!/WATCH|NO BET|PASS|MARKET BUILD/.test(q.winner)).map(q=>[`${q.away} @ ${q.home}`,q.winner,q.conf,q.market]);const S=(icon,title,status,desc,qcs=[])=>({icon,title,meta:`${title} • ${status} • SEP 17 • 12PM`,kicker:`${title} DAILY PREDICTIONS`,description:desc,chips:[[status,'purple'],['SEP 17 • 12PM','gold']],hotTop:[],winners:[],twenty:[],twentyNote:desc,qcTitle:`${title} — ${status}`,qcs});D.updated='Updated Sep 17, 2026 • 12:00 PM PT — MIDDAY REFRESH';

/* MLB: games already in progress at noon PT are deliberately removed from the prediction board. */
const MLB={icon:'⚾',title:'MLB',meta:'MLB • THURSDAY SEPTEMBER 17, 2026 • 12PM REFRESH',kicker:'MLB DAILY PREDICTIONS',description:'Midday hard validity check completed. MIL-PIT, LAD-CIN and ATH-TB were already in progress and are removed from active predictions. SD-COL has confirmed lineups. Five evening games remain pre-lineup. A newly verified Framber Valdez strikeout market is promoted; no completed/in-progress game is backfilled.',chips:[['6 FUTURE / PREGAME QCs','green'],['NO IN-PROGRESS BACKFILL','purple'],['SEP 17 • 12PM','gold']],qcs:[
Q('12:10 PM PT','SD','COL','Padres','65%','Michael King (R) vs Tanner Gordon (R) • BOTH LINEUPS CONFIRMED',['Padres ML • 65%'],'Both orders are confirmed: San Diego has Tatis/Machado/Merrill/Bogaerts; Colorado has McCarthy/Norby/Carrigg/Rumfield. King remains the stronger starter, but Coors volatility caps confidence.'),
Q('4:15 PM PT','PHI','NYM','Phillies lean','57%','Aaron Nola (R) vs Nolan McLean (R) • lineups pending',['Phillies ML lean • 57%','Game NRFI -106 FanDuel • 56%'],'Philadelphia has materially greater postseason incentive. FanDuel posted NRFI -106 today; keep confidence modest until both lineups post.'),
Q('4:15 PM PT','KC','HOU','Astros lean','55%','Seth Lugo (R) vs HOU starter TBD • lineups pending',['Astros ML lean • 55%'],'Houston starter remains unverified at noon; no player prop is promoted from an incomplete pitching matchup.'),
Q('4:40 PM PT','DET','CWS','Tigers','63%','Framber Valdez (L) vs Erick Fedde (R) • lineups pending',['Tigers ML • 63%','Framber Valdez OVER 4.5 strikeouts (-104 FanDuel) • 62%'],'FanDuel verifies Valdez O4.5 K at -104 this afternoon. LEGZ likes the low threshold; exact price still needs entry-time confirmation.'),
Q('5:05 PM PT','BOS','TEX','Red Sox lean','55%','Sonny Gray (R) vs Tyler Alexander (L) • lineups pending',['Red Sox ML lean • 55%','Game NRFI -122 FanDuel • 58%'],'Texas starter is verified as Tyler Alexander. FanDuel has NRFI -122; player thresholds remain gated until lineups post.'),
Q('6:38 PM PT','MIN','LAA','Twins lean','56%','Taj Bradley (R) vs Walbert Ureña (R) • lineups pending',['Twins ML lean • 56%','Game NRFI -130 FanDuel • 59%'],'FanDuel has NRFI -130. No stale batter prop is reused before lineups.') ]};MLB.winners=rows(MLB);MLB.hotTop=[['Padres','Game winner','65%','Both lineups confirmed; Michael King remains the strongest active starter/club edge.'],['Tigers','Game winner','63%','Valdez/Fedde pitching edge remains favorable.'],['Framber Valdez','OVER 4.5 strikeouts','62%','FanDuel -104 verified Thursday afternoon; low K threshold is the strongest newly verified MLB player market.'],['Twins-Angels','NRFI','59%','FanDuel -130 verified today; moderate edge only.'],['Red Sox-Rangers','NRFI','58%','FanDuel -122 verified today; moderate edge only.']];MLB.twenty=[['MLB','Framber Valdez','Over 4.5 strikeouts','-104 FanDuel','62%','★★★☆☆','🔥']];MLB.twentyNote='20 PIECE remains player-prop only. Valdez O4.5 K is the only noon MLB player threshold promoted after exact-market verification; other evening player markets remain WATCH pending lineup/threshold synchronization.';

const NFL=S('🏈','NFL','TODAY’S QC','Detroit at Buffalo remains 5:15 PM PT. Detroit starting OL Christian Mahogany and Blake Miller are OUT. Noon research adds independently published TNF markets: Sam LaPorta U46.5 receiving, Jahmyr Gibbs O4.5 receptions and Josh Allen O31.5 rushing. Buffalo’s Week 1 shift to 13 personnel and increased downfield passing is retained as JINX context.');NFL.qcs=[Q('5:15 PM PT','DET','BUF','Bills ML lean','64%','Current public range varies by book; Hard Rock snapshot BUF -5.5 / ML -240 / total 55',['Jared Goff UNDER 270.5 passing yards • LEGZ 64% + JINX 5% = L&J 69%','Sam LaPorta UNDER 46.5 receiving yards (-115) • LEGZ 66% + JINX 2% = L&J 68%','Jahmyr Gibbs OVER 4.5 receptions (+115) • LEGZ 61% + JINX 2% = L&J 63%','Josh Allen OVER 31.5 rushing yards • LEGZ 62% + JINX 3% = L&J 65%'],'JINX: Detroit’s two missing starting linemen still strengthen Goff downside. Buffalo used 13 personnel on 39% of Week 1 snaps and Allen pushed the ball deeper, supporting volatility rather than blind favorite exposure.')];NFL.winners=rows(NFL);NFL.hotTop=[['Jared Goff','UNDER 270.5 passing yards','69%','LEGZ 64% + JINX 5% = L&J 69% • JINX: Two starting Detroit linemen are out; protection risk strengthens the under.'],['Sam LaPorta','UNDER 46.5 receiving yards','68%','LEGZ 66% + JINX 2% = L&J 68% • Buffalo allowed only 29.6 TE receiving yards/game in 2025 and held Dalton Schultz to 35 in Week 1.'],['Josh Allen','OVER 31.5 rushing yards','65%','LEGZ 62% + JINX 3% = L&J 65% • Current TNF prop published today.'],['Bills','Game winner lean','64%','Home field and Detroit OL attrition support Buffalo, but the spread has moved enough across books to keep this below SNS.']];NFL.twenty=[['NFL','Jared Goff','Under 270.5 passing yards','PrizePicks threshold','69%','★★★★☆','🔥'],['NFL','Sam LaPorta','Under 46.5 receiving yards','-115 published market','68%','★★★★☆','🔥'],['NFL','Josh Allen','Over 31.5 rushing yards','published market','65%','★★★☆☆','🔥'],['NFL','Jahmyr Gibbs','Over 4.5 receptions','+115 published market','63%','★★★☆☆','🔥']];NFL.twentyNote='Noon player board uses current published TNF thresholds. Prices/thresholds remain entry-time sensitive.';

const WNBA={icon:'🏀',title:'WNBA',meta:'WNBA • THURSDAY SEPTEMBER 17, 2026 • 12PM REFRESH',kicker:'WNBA DAILY PREDICTIONS',description:'Five-game post-FIBA slate remains intact. Noon prop sweep adds current published thresholds for Allisha Gray, Shakira Austin and Paige Bueckers. Availability remains a key risk: Sonia Citron is out, Georgia Amoore is questionable, and Bueckers recently managed patellar tendinitis during the World Cup.',chips:[['5 GAME QCs','green'],['CURRENT PLAYER PROPS','purple'],['SEP 17 • 12PM','gold']],qcs:[
Q('4:30 PM PT','CON','ATL','Dream','88%','Atlanta heavy favorite • exact price recheck',['Dream ML • 88%','Allisha Gray OVER 24.5 PRA • LEGZ 78% + JINX 2% = L&J 80%'],'LEGZ: Gray has averaged 35 PRA in two meetings with Connecticut. That threshold is asking for less than her matchup baseline.'),
Q('5:00 PM PT','WSH','CHI','Mystics lean','54%','Washington favorite • availability-sensitive',['Shakira Austin OVER 26.5 points + rebounds • LEGZ 74% + JINX 3% = L&J 77%'],'Austin averaged 30.0 points+rebounds over her final 13 games before the break; Chicago has been the league’s weakest rebounding environment. Team side remains low confidence because of absences.'),
Q('5:00 PM PT','LA','DAL','Wings','69%','Dallas favored • exact price recheck',['Paige Bueckers OVER 27.5 points + assists • LEGZ 69% − JINX 5% = L&J 64%'],'JINX: I like the matchup less than I like the knee. Recent patellar-tendinitis management is enough to cut five points from LEGZ; don’t pretend workload is guaranteed.'),
Q('7:00 PM PT','PHX','POR','PASS','50%','Near pick’em',['WATCH / NO BET'],'No sufficient team-side edge at noon; do not force a winner.'),
Q('7:00 PM PT','LV','SEA','Aces','78%','Las Vegas strong favorite • exact spread recheck',['Aces ML • 78%'],'Team-strength gap remains substantial; final availability receives pregame check.') ]};WNBA.winners=rows(WNBA);WNBA.hotTop=[['Atlanta Dream','Game winner','88%','Strongest WNBA team-side edge. LEGZ: This one has more cushion than a courtside recliner.'],['Allisha Gray','OVER 24.5 PRA','80%','LEGZ 78% + JINX 2% = L&J 80% • Two prior games vs Connecticut: 35 PRA average.'],['Las Vegas Aces','Game winner','78%','Large team-strength gap remains intact.'],['Shakira Austin','OVER 26.5 points + rebounds','77%','LEGZ 74% + JINX 3% = L&J 77% • Strong pre-break form plus favorable Chicago rebounding matchup.'],['Paige Bueckers','OVER 27.5 points + assists','64%','LEGZ 69% − JINX 5% = L&J 64% • JINX: Recent knee management makes the workload too important to ignore.']];WNBA.twenty=[['WNBA','Allisha Gray','Over 24.5 PRA','current published threshold','80%','★★★★★','🔥'],['WNBA','Shakira Austin','Over 26.5 points + rebounds','current published threshold','77%','★★★★☆','🔥'],['WNBA','Paige Bueckers','Over 27.5 points + assists','current published threshold','64%','★★★☆☆','']];WNBA.twentyNote='Noon 20 PIECE uses current Sep 17 published thresholds. Bueckers is intentionally discounted by JINX for recent knee-management uncertainty.';

const NCAA=S('🏈','NCAA FOOTBALL','NEXT ANNOUNCED EVENT QCs','No monitored FBS target game today; Sep 18–19 player markets remain under active LSI acquisition. Weekend props stay visible in the native LSI layer and are not replaced by game-day-only WATCH labels.');
const TEN=S('🎾','TENNIS','TODAY’S TOURNAMENT QCs','Current WTA tournament state retained. Taylor Townsend withdrew from Guadalajara because of illness, so no stale Townsend prediction is permitted. Official OOP / FOLLOWS language remains required.');TEN.qcs=[Q('SEP 17 • OFFICIAL OOP / FOLLOWS','Liudmila Samsonova','Marta Kostyuk','WATCH','—','Guadalajara • exact current market recheck'),Q('SEP 17 • OFFICIAL OOP / FOLLOWS','WTA field','São Paulo','WATCH','—','Current tournament play • official OOP language only')];TEN.winners=[];TEN.hotTop=[];TEN.twenty=[];TEN.twentyNote='No participant prop promoted without a synchronized current threshold.';
const FW=S('🌍🏀','FIBA WOMEN','NEXT ANNOUNCED EVENT','2026 Women’s World Cup concluded Sep 13; no Sep 17 senior World Cup game.');const FM=S('🌍🏀','FIBA MEN','NEXT ANNOUNCED EVENT','No monitored senior FIBA Men event verified for Sep 17.');const UFC=S('🥊','UFC','NEXT ANNOUNCED EVENT QCs','No Sep 17 UFC event. UFC 331: Van vs Pantoja 2 remains Sep 19; Ortega vs Moicano remains removed due to Ortega injury.');UFC.qcs=[Q('SEP 19 • 6:00 PM PT MAIN CARD','Alexandre Pantoja','Joshua Van','Van lean','54%','UFC 331 flyweight title • price recheck',['Van ML lean • 54%'])];const BOX=S('🥊','BOXING','NEXT ANNOUNCED EVENT QCs','No major monitored boxing event today; next monitored Sep 26 card remains event-level WATCH.');BOX.qcs=[Q('SEP 26 • TIME WATCH','Kenzo Biyong','Tony Ferguson',W,'—','Next monitored boxing event')];const NBA=S('🏀','NBA','SEASON START / OFFSEASON STATUS','NBA regular season has not begun; no stale predictions retained.');const NHL=S('🏒','NHL','SEASON START / OFFSEASON STATUS','NHL regular season has not begun; no stale predictions retained.');const NCB=S('🏀','NCAA BASKETBALL','SEASON START / OFFSEASON STATUS','NCAA basketball season has not begun; no stale predictions retained.');D.sports={MLB,NFL,NBA,WNBA,NHL,FIBA_Men:FM,FIBA_Women:FW,NCAA_Football:NCAA,NCAA_Basketball:NCB,UFC,Boxing:BOX,Tennis:TEN};})();