/* LEGZ & JINX — ISOLATED /live/ DATA — Sep 11, 2026 • 2:00 AM PT */
window.LJ_LIVE_DATA=(()=>{const WATCH="WATCH — exact current live market/state not independently synchronized",MODEL="MODEL-ONLY FINISH FORECAST — not an executable sportsbook line";const nav=[["MLB","⚾","MLB.html"],["NFL","🏈","NFL.html"],["NBA","🏀","NBA.html"],["WNBA","🏀","WNBA.html"],["NHL","🏒","NHL.html"],["FIBA MEN","🌍🏀","FIBA_Men.html"],["FIBA WOMEN","🌍🏀","FIBA_Women.html"],["NCAA FOOTBALL","🏈","NCAA_Football.html"],["NCAA BASKETBALL","🏀","NCAA_Basketball.html"],["TENNIS","🎾","Tennis.html"],["UFC","🥊","UFC.html"],["BOXING","🥊","Boxing.html"]];const empty=(icon,title,detail,status="NO LIVE EVENT")=>({icon,title,meta:`${title} • SEP 11 • 2:00 AM PT`,kicker:`${title} LIVE`,description:detail,chips:[[status,"purple"],["WATCH","gold"],["NO STALE FILLER","gold"]],hotTop:[],winners:[],twenty:[],twentyNote:"No current live selection clears the verification gate.",qcTitle:`${title} — LIVE QUICKIES`,qcs:[]});const sports={
MLB:empty("⚾","MLB","No MLB game is verified in progress. September 11 MLB games begin later today; completed September 10 games remain removed from active LIVE presentation."),
NFL:empty("🏈","NFL","No NFL game is verified in progress. San Francisco at Los Angeles Rams is complete and remains removed from active LIVE presentation."),
NBA:empty("🏀","NBA","No NBA game is verified in progress."),
WNBA:empty("🏀","WNBA","No WNBA game is verified in progress.","WATCH"),
NHL:empty("🏒","NHL","No NHL game is verified in progress."),
FIBA_Men:empty("🌍🏀","FIBA MEN","No monitored senior men's FIBA event is independently verified in progress.","WATCH"),
FIBA_Women:empty("🌍🏀","FIBA WOMEN","Official FIBA Women's World Cup game center reports Live (0). There are no Women's World Cup games scheduled for September 11; completed September 10 quarterfinals are not carried forward as LIVE.","WATCH"),
NCAA_Football:empty("🏈","NCAA FOOTBALL","No NCAA Football game is verified in progress.","WATCH"),
NCAA_Basketball:empty("🏀","NCAA BASKETBALL","No NCAA Basketball game is verified in progress."),
Tennis:empty("🎾","TENNIS","No monitored U.S. Open match is verified in progress. September 11 competition begins later today with the women's doubles final and other daytime matches, followed by men's singles semifinals; no schedule-only event is promoted to LIVE.","WATCH"),
UFC:empty("🥊","UFC","No UFC card is verified in progress. Noche UFC remains scheduled for September 12."),
Boxing:empty("🥊","BOXING","No monitored boxing bout is verified in progress. Red Owl Boxing Boxfest XX prelims are scheduled for 4:00 PM PT and the DAZN main card for 6:00 PM PT on September 11; the event is not yet live.","WATCH")
};const statuses=[["MLB","NO LIVE EVENT","No in-progress MLB game verified"],["NFL","NO LIVE EVENT","No in-progress NFL game verified"],["NBA","NO LIVE EVENT","No in-progress game verified"],["WNBA","WATCH","No in-progress event verified"],["NHL","NO LIVE EVENT","No in-progress game verified"],["FIBA_Men","WATCH","No monitored senior men's event verified live"],["FIBA_Women","WATCH","Official FIBA game center reports Live (0)"],["NCAA_Football","WATCH","No in-progress game verified"],["NCAA_Basketball","NO LIVE EVENT","No in-progress game verified"],["Tennis","WATCH","September 11 U.S. Open sessions begin later today"],["UFC","NO LIVE EVENT","No UFC card in progress"],["Boxing","WATCH","Boxfest XX begins later September 11"]];const home={meta:"L&J LIVE • SEPTEMBER 11, 2026 • 2:00 AM PT",kicker:"L&J LIVE PREDICTIONS",title:"LEGZ & JINX — LIVE PREDICTIONS",description:"No monitored event currently clears the verified LIVE gate. Completed events remain removed from active presentation. FIBA Women officially reports Live (0). Tennis and boxing remain WATCH for scheduled September 11 action later today; no event is promoted from schedule alone.",chips:[["NO VERIFIED LIVE EVENTS","purple"],["MULTI-SOURCE GATE ACTIVE","gold"],["NO STALE OR FABRICATED DATA","purple"]],hotTop:[],winners:[],twenty:[],twentyNote:"No current live selection clears the verification gate. Model-only forecasts and executable in-play markets are intentionally omitted when no event is verified live."};return{updated:"SEP 11, 2026 • 2:00 AM PT LIVE SNAPSHOT",nav,sports,statuses,home,WATCH,MODEL};})();